library(tidyverse)
source("./modlib/constants_equations_v3.R")



#=============================================#
# Nutrient requirements based on NASEM (2024) #
#=============================================#

###################################################################################################################
# Variable conversion
# 20240604 현재는 어쩔 수 없이 이렇게 
###################################################################################################################

# Animal_input(an)에서 읽는 animal information
# Model_inputs와 CNUCNM input을 매칭시킴

NASEM_dairy_requirements<-function(input_data_rev,feed_data_rev, diet_composition_rev){
  # DietID <- as.numeric(an$DietID)  #need to maintain TrtID as an input for the function to work with meta data.
  An_StatePhys <- ifelse(input_data_rev$stage_name == "calf", "Calf",
                         ifelse(input_data_rev$stage_name == "growing", "Heifer",
                                ifelse(input_data_rev$stage_name == "lactating", "Lactating Cow",
                                       ifelse(input_data_rev$stage_name == "drying", "Dry Cow", NA))))
  An_Breed <- input_data_rev$breed_name
  An_305RHA_MlkTP <- 1.02 #as.numeric(ref_milk_yield.kg*ref_milk_tp.p/100)
  An_BW_mature <- as.numeric(input_data_rev$mature_bw)  #note case is wrong for M in mature
  An_AgeDay <- as.numeric(input_data_rev$age.month*365)
  An_BW <- as.numeric(input_data_rev$full_bw)
  An_BCS <- as.numeric(input_data_rev$bcs_dairy)
  An_Parity_rl <- min(as.numeric(input_data_rev$lact_no),2) 
  An_LactDay <- as.numeric(input_data_rev$milk.day)
  
  An_GestLength <- 283 #as.numeric(pregnancy.day)
  An_AgeCalv1st <- as.numeric(input_data_rev$tca.month*30.4) # Deleted from version 2020-02-15
  
  Monensin_eqn  <- 0 # added to version 2020-02-15
  
  An_AgeConcept1st <- An_AgeCalv1st-283 #An_AgeCalv1st-pregnancy.day
  An_GestDay <- as.numeric(input_data_rev$preg.day)
  An_DIMConcept <- as.numeric(min(input_data_rev$ci.month*30.4-pregnancy.day,input_data_rev$milk.day))
  
  Env_Topo <- 0
  Env_DistParlor <- 0
  Env_DistParlor <- ifelse(is.na(Env_DistParlor), 0, Env_DistParlor)  #Abbas needs to provide a default value for this
  Env_TripsParlor <- 0
  Env_TripsParlor <- ifelse(is.na(Env_TripsParlor), 4, Env_TripsParlor)  #Abbas needs to provide a default value for this
  Env_TempCurr <- 15
  Env_TempCurr <- ifelse(is.na(Env_TempCurr), 24, Env_TempCurr)  #Abbas needs to provide a default value for this
  
  Fet_BWbrth <- as.numeric(input_data_rev$calf_bw)
  Trg_RsrvGain <- 0
  Trg_FrmGain <- as.numeric(input_data_rev$target_adg)
  Trg_MilkProd <- as.numeric(input_data_rev$milk_yield)
  Trg_MilkFatp <- as.numeric(input_data_rev$milk_fat)
  Trg_MilkTPp <- as.numeric(input_data_rev$milk_cp*0.951)
  Trg_MilkLacp <- 4.85
  
  Trg_Dt_DMIn <- as.numeric(diet_composition_rev$target_dmi)
  
  # 이것은 diet에서 읽음
  Fd_DMInp <- as.numeric(feed_data_rev$dm.kg/diet_composition_rev$target_dmi)
  
  An_AgeDryFdStart <- 14
  
  # DMIn_eqn <- as.numeric(an$DMIn_eqn)
  FrmGain_eqn <- 0
  RsrvGain_eqn <- 0
  # RUP_eqn <- as.numeric(an$RUP_eqn)
  # mFat_eqn <- as.numeric(an$mFat_eqn)
  # MiN_eqn <- as.numeric(an$MiN_eqn)
  mLac_eqn <- 0
  mProd_eqn <- 0
  mPrt_eqn <- 0
  # #... mPrt_eqn <- 1 #temp override
  # Use_DNDF_IV <- as.numeric(an$Use_DNDF_IV)
  # message("Use_DNDF_IV = ", Use_DNDF_IV)
  # 
  # # two new flags. Their names in R-Code are different than thier name in C-Sharp
  # RumDevDisc_Clf <- as.numeric(an$Discount_ME_eqn)
  # NonMilkCP_ClfLiq <- as.numeric(an$Milk_Replacer_eqn)
  
  #################################################
  # Seo - to prevent errors in calf equations
  Dt_DMIn_ClfLiq<-0
  Dt_DMIn_ClfStrt<-0
  #################################################
  
  ##### Fill missing inputs with 0 and add scalars as needed to the f DF for use in Diet Calculations ###########
  #Should also check for missing values in the inputs and trap them or stop the function.
  
  #################################################
  # Don't know
  # f$An_StatePhys <- as.vector(An_StatePhys)   
  #################################################
  
  An_GestDay <- ifelse(An_GestDay < 0 | is.na(An_GestDay), 0, An_GestDay);	#Trap NA and negative values
  An_GestDay <- ifelse(An_GestDay > An_GestLength + 10, 0,  An_GestDay)
  
  #Determine some additional physiology values
  An_PrePartDay <- An_GestDay - An_GestLength
  An_PrePartWk <- An_PrePartDay/7
  
  #Calculate day postpartum and trap nonsense values
  An_PostPartDay <- ifelse(An_LactDay <= 0, 0, An_LactDay)
  An_PostPartDay <- ifelse(An_LactDay > 100, 100, An_LactDay)
  
  An_MBW <- An_BW^0.75
  Trg_BWgain <- Trg_FrmGain + Trg_RsrvGain		#This could also be generated by prediction equations
  Trg_BWgain_g <- Trg_BWgain * 1000
  
  #Determine lower (LCT) and upper (UCT) critical temperatures, degrees C for thermal stress
  LCT <- 15						#calf < 3 wks of age
  LCT <- ifelse(An_AgeDay > 21, 5, LCT)	#calf > 3 wks of age
  UCT <- 25						#calf
  
  
  
  
  ###################################################################################################################
  # supply 모델에서 계산된 Nutrient intake 계산 결과를 여기에
  
  An_DMIn<-diet_composition_rev$target_dmi
  
  An_MPIn_g<-diet_composition_rev$diet_mp.g
  An_MPIn <- An_MPIn_g / 1000
  An_CPIn <- diet_composition_rev$target_dmi*diet_composition_rev$diet_cp.p/100
  An_NIn_g <- An_CPIn*0.16*1000
  
  # RDP + RUP*0.8이 digestible 
  An_DigNtIn_g<-((100-diet_composition_rev$diet_rupx.p.cp)/100 + diet_composition_rev$diet_rupx.p.cp/100*0.8)*An_NIn_g
  
  An_GEIn<-diet_composition_rev$diet_ge.mcal.kg*diet_composition_rev$target_dmi
  An_DEIn<-diet_composition_rev$diet_de.mcal.kg*diet_composition_rev$target_dmi
  An_MEIn<-diet_composition_rev$diet_me.mcal.kg*diet_composition_rev$target_dmi
  # 이것은 NASEM(2021)에 따라
  An_NEIn <- An_MEIn * 0.66
  
  ###################################################################################################################
  
  
  
  
  ########################################################################################################
  #                                  Nutrient Utilization                                                #
  ########################################################################################################
  #### AA Composition of Proteins, g hydrated AA/100 g of TP ####
  # all were corrected for incomplete recovery during a 24h acid hydrolysis
  
  # Milk Protein AA Composition, g/100 g of TP
  Mlk_Arg_TP <- 3.74
  Mlk_His_TP <- 2.92
  Mlk_Ile_TP <- 6.18
  Mlk_Leu_TP <- 10.56
  Mlk_Lys_TP <- 8.82
  Mlk_Met_TP <- 3.03
  Mlk_Phe_TP <- 5.26
  Mlk_Thr_TP <- 4.62
  Mlk_Trp_TP <- 1.65
  Mlk_Val_TP <- 6.90
  
  #Body Protein AA Composition, g/100 g of TP
  Body_Arg_TP <- 8.20
  Body_His_TP <- 3.04
  Body_Ile_TP <- 3.69
  Body_Leu_TP <- 8.27
  Body_Lys_TP <- 7.90
  Body_Met_TP <- 2.37
  Body_Phe_TP <- 4.41
  Body_Thr_TP <- 4.84
  Body_Trp_TP <- 1.05
  Body_Val_TP <- 5.15
  
  #Endogenous Urinary Protein AA Composition, g/100 g of TP; these are set equal to body protein AA comp
  Ur_ArgEnd_TP <- 8.20
  Ur_HisEnd_TP <- 3.04
  Ur_IleEnd_TP <- 3.69
  Ur_LeuEnd_TP <- 8.27
  Ur_LysEnd_TP <- 7.90
  Ur_MetEnd_TP <- 2.37
  Ur_PheEnd_TP <- 4.41
  Ur_ThrEnd_TP <- 4.84
  Ur_TrpEnd_TP <- 1.05
  Ur_ValEnd_TP <- 5.15
  
  #Metabolic Fecal Protein AA Composition, g/100 g of TP
  Fe_ArgMetab_TP <- 5.90
  Fe_HisMetab_TP <- 3.54
  Fe_IleMetab_TP <- 5.39
  Fe_LeuMetab_TP <- 9.19
  Fe_LysMetab_TP <- 7.61
  Fe_MetMetab_TP <- 1.73
  Fe_PheMetab_TP <- 5.28
  Fe_ThrMetab_TP <- 7.36
  Fe_TrpMetab_TP <- 1.79
  Fe_ValMetab_TP <- 7.01
  
  #Scurf Protein AA Composition, g/100 g of TP
  Scrf_Arg_TP <- 9.60
  Scrf_His_TP <- 1.75
  Scrf_Ile_TP <- 2.96
  Scrf_Leu_TP <- 6.93
  Scrf_Lys_TP <- 5.64
  Scrf_Met_TP <- 1.40
  Scrf_Phe_TP <- 3.61
  Scrf_Thr_TP <- 4.01
  Scrf_Trp_TP <- 0.73
  Scrf_Val_TP <- 4.66
  
  
  ############################################################################################
  #                             Maintenance Export Proteins                                  #
  ############################################################################################
  
  ############################################################################################
  # Seo - NASEM (2016)의 MP for maintenance = 3.8*SBW^0.75 이용 
  # NASEM (2016, p181) - assuming CP*0.64 = MP
  # Therefore, CP for maintenance = 3.8 / 0.64 * sBW^0.75 
  
  ###########################################################################################
  
  
  ############## Scurf Protein and AA#
  Body_NP_CP <- 0.86    #NP content of all body proteins, g NP/g CP
  
  
  
  
  # Scrf_CP_g <- 0.20 * An_BW^0.60
  # Scrf_CP_g <- ifelse(An_StatePhys == "Calf", 0.219*An_BW^0.60, Scrf_CP_g)
  # Scrf_NP_g <- Scrf_CP_g * Body_NP_CP
  # Scrf_NP <- Scrf_NP_g * 0.001
  # Scrf_N_g <- Scrf_CP_g * 0.16
  # Scrf_Arg_g <- Scrf_NP_g * Scrf_Arg_TP / 100
  # Scrf_His_g <- Scrf_NP_g * Scrf_His_TP / 100
  # Scrf_Ile_g <- Scrf_NP_g * Scrf_Ile_TP / 100
  # Scrf_Leu_g <- Scrf_NP_g * Scrf_Leu_TP / 100
  # Scrf_Lys_g <- Scrf_NP_g * Scrf_Lys_TP / 100
  # Scrf_Met_g <- Scrf_NP_g * Scrf_Met_TP / 100
  # Scrf_Phe_g <- Scrf_NP_g * Scrf_Phe_TP / 100
  # Scrf_Thr_g <- Scrf_NP_g * Scrf_Thr_TP / 100
  # Scrf_Trp_g <- Scrf_NP_g * Scrf_Trp_TP / 100
  # Scrf_Val_g <- Scrf_NP_g * Scrf_Val_TP / 100
  
  # As a fraction of absorbed
  # Seo - Absorbed value를 알아야 하므로 제외
  
  # ScrfArg_AbsArg <- Scrf_Arg_g / Abs_Arg_g 
  # ScrfHis_AbsHis <- Scrf_His_g / Abs_His_g 
  # ScrfIle_AbsIle <- Scrf_Ile_g / Abs_Ile_g 
  # ScrfLeu_AbsLeu <- Scrf_Leu_g / Abs_Leu_g 
  # ScrfLys_AbsLys <- Scrf_Lys_g / Abs_Lys_g 
  # ScrfMet_AbsMet <- Scrf_Met_g / Abs_Met_g 
  # ScrfPhe_AbsPhe <- Scrf_Phe_g / Abs_Phe_g 
  # ScrfThr_AbsThr <- Scrf_Thr_g / Abs_Thr_g 
  # ScrfTrp_AbsTrp <- Scrf_Trp_g / Abs_Trp_g 
  # ScrfVal_AbsVal <- Scrf_Val_g / Abs_Val_g 
  
  
  #### Metabolic Fecal AA (g/d) Predictions ####
  # Seo - Fe_NPend를 알아야 하는데... 이것은 계산을 해야하지 않을까 싶네...
  # 일단 amino acid는 제외를 할 것이니까 제외
  
  # Fe_ArgMet_g <- Fe_NPend_g * Fe_ArgMetab_TP / 100
  # Fe_HisMet_g <- Fe_NPend_g * Fe_HisMetab_TP / 100
  # Fe_IleMet_g <- Fe_NPend_g * Fe_IleMetab_TP / 100
  # Fe_LeuMet_g <- Fe_NPend_g * Fe_LeuMetab_TP / 100
  # Fe_LysMet_g <- Fe_NPend_g * Fe_LysMetab_TP / 100
  # Fe_MetMet_g <- Fe_NPend_g * Fe_MetMetab_TP / 100
  # Fe_PheMet_g <- Fe_NPend_g * Fe_PheMetab_TP / 100
  # Fe_ThrMet_g <- Fe_NPend_g * Fe_ThrMetab_TP / 100
  # Fe_TrpMet_g <- Fe_NPend_g * Fe_TrpMetab_TP / 100
  # Fe_ValMet_g <- Fe_NPend_g * Fe_ValMetab_TP / 100
  
  # As a fraction of absorbed
  # Fe_ArgMet_AbsArg <- Fe_ArgMet_g / Abs_Arg_g 
  # Fe_HisMet_AbsHis <- Fe_HisMet_g / Abs_His_g 
  # Fe_IleMet_AbsIle <- Fe_IleMet_g / Abs_Ile_g 
  # Fe_LeuMet_AbsLeu <- Fe_LeuMet_g / Abs_Leu_g 
  # Fe_LysMet_AbsLys <- Fe_LysMet_g / Abs_Lys_g 
  # Fe_MetMet_AbsMet <- Fe_MetMet_g / Abs_Met_g 
  # Fe_PheMet_AbsPhe <- Fe_PheMet_g / Abs_Phe_g 
  # Fe_ThrMet_AbsThr <- Fe_ThrMet_g / Abs_Thr_g 
  # Fe_TrpMet_AbsTrp <- Fe_TrpMet_g / Abs_Trp_g 
  # Fe_ValMet_AbsVal <- Fe_ValMet_g / Abs_Val_g 
  
  # #### Urinary Endogenous N, CP, and AA (g/d) Predictions ####
  # Ur_Nend_Urea_g <- 0.010 * An_BW              #endogenous urea N, g/d
  # Ur_Nend_Creatn_g <- 0.00946 * An_BW          #endogenous creatinine N, g/d
  # Ur_Nend_Creat_g <- Ur_Nend_Creatn_g * 0.37   #endogenous creatine N, g/d
  # Ur_Nend_PD_g <- 0.0271 * An_BW^0.75          #endogenous purine derivative N, g/d
  # fN_3MH = (3*14)/169
  # Ur_NPend_3MH_g <- (7.84+0.55*An_BW)/1000      #endogenous 3-methyl-histidine NP, g/d
  # Ur_Nend_3MH_g <- Ur_NPend_3MH_g * fN_3MH 
  # Ur_Nend_sum_g <- (Ur_Nend_Urea_g + Ur_Nend_Creatn_g + Ur_Nend_Creat_g +Ur_Nend_PD_g + 
  #                     Ur_Nend_3MH_g)/(1-0.46)
  # Ur_Nend_Hipp_g <- Ur_Nend_sum_g * 0.46             #46% of the total end is hippuric acid
  # 
  Ur_Nend_g <- 0.053 * An_BW                    #approximates Ur_Nend_sum
  Ur_NPend_g <- Ur_Nend_g * 6.25
  Ur_NPend_g <- ifelse(An_StatePhys == "Calf", 2.75*An_BW^0.50, Ur_NPend_g )  #Calf
  # Ur_NPend <- Ur_NPend_g * 0.001
  # Ur_MPend <- Ur_NPend
  # Ur_EAAend_g <- 0.010 * 6.25 * An_BW  #includes only the MP-EAA used for urea and 3-MHis.
  # 
  # Ur_ArgEnd_g <- Ur_EAAend_g * Ur_ArgEnd_TP / 100
  # Ur_HisEnd_g <- Ur_EAAend_g * Ur_HisEnd_TP / 100 + Ur_NPend_3MH_g #Urea plus 3-MHis
  # Ur_IleEnd_g <- Ur_EAAend_g * Ur_IleEnd_TP / 100
  # Ur_LeuEnd_g <- Ur_EAAend_g * Ur_LeuEnd_TP / 100
  # Ur_LysEnd_g <- Ur_EAAend_g * Ur_LysEnd_TP / 100
  # Ur_MetEnd_g <- Ur_EAAend_g * Ur_MetEnd_TP / 100
  # Ur_PheEnd_g <- Ur_EAAend_g * Ur_PheEnd_TP / 100
  # Ur_ThrEnd_g <- Ur_EAAend_g * Ur_ThrEnd_TP / 100
  # Ur_TrpEnd_g <- Ur_EAAend_g * Ur_TrpEnd_TP / 100
  # Ur_ValEnd_g <- Ur_EAAend_g * Ur_ValEnd_TP / 100
  # 
  # # As a fraction of absorbed
  # Ur_ArgEnd_AbsArg <- Ur_ArgEnd_g / Abs_Arg_g 
  # Ur_HisEnd_AbsHis <- Ur_HisEnd_g / Abs_His_g 
  # Ur_IleEnd_AbsIle <- Ur_IleEnd_g / Abs_Ile_g 
  # Ur_LeuEnd_AbsLeu <- Ur_LeuEnd_g / Abs_Leu_g 
  # Ur_LysEnd_AbsLys <- Ur_LysEnd_g / Abs_Lys_g 
  # Ur_MetEnd_AbsMet <- Ur_MetEnd_g / Abs_Met_g 
  # Ur_PheEnd_AbsPhe <- Ur_PheEnd_g / Abs_Phe_g 
  # Ur_ThrEnd_AbsThr <- Ur_ThrEnd_g / Abs_Thr_g 
  # Ur_TrpEnd_AbsTrp <- Ur_TrpEnd_g / Abs_Trp_g 
  # Ur_ValEnd_AbsVal <- Ur_ValEnd_g / Abs_Val_g 
  # 
  # Ur_EAAEnd_g <- Ur_ArgEnd_g + Ur_HisEnd_g + Ur_IleEnd_g + Ur_LeuEnd_g + 
  #   Ur_LysEnd_g + Ur_MetEnd_g + Ur_PheEnd_g + Ur_ThrEnd_g + Ur_TrpEnd_g + 
  #   Ur_ValEnd_g 
  
  # An_NPm_Use <- Scrf_NP_g + Fe_NPend_g + Ur_NPend_g
  # An_CPm_Use <- Scrf_CP_g + Fe_CPend_g + Ur_NPend_g
  
  ###########################################################################################
  # Fe_NPend_g를 어디서 계산하는지 안보인다. 
  # Seo
  # NASEM(2016)에 따라서 단순하게 계산
  An_CPm_Use<-3.8 / 0.64 * input_data_rev$shrunk_bw^0.75
  An_NPm_Use <-An_CPm_Use*Body_NP_CP
  
  
  
  
  ############################################################################################
  #                    Milk protein and AA output                                            #
  ############################################################################################
  mPrt_eqn <- 0 #0 for target milk protein, 1 for NRC 2020 prediction, 2 for VT prediction
  mPrt_parmset <- mPrt_eqn
  if(mPrt_parmset == 0) {mPrt_parmset <- 1} #Trap 0 choice as used to select from the parameters vector
  
  # #NRC derived Coefficients from Dec. 20, 2020 solutions. AIC=10,631
  # #VT1 derived Coefficients from Dec. 20, 2020 solutions. AIC=10,629
  # #VT2 derived Coefficients from April, 2022 solutions after further data cleaning, AIC=10,405. In publication.
  # #Source copies of the mPrt equation coefficients (NRC, VT1, VT2)
  # #                       NRC,   VT1,     VT2
  # mPrt_Int_src <-      c(-97.0, -141,     -73.7) 
  # mPrt_k_BW_src <-     c(-0.4201,-0.4146, -.3663)
  # mPrt_k_DEInp_src <-  c(10.79,  10.65,   0)
  # mPrt_k_DigNDF_src <- c(-4.595, -4.62,   0)
  # mPrt_k_DEIn_StFA_src <-  c(0,  0,       10.87)         #DEStIn + DErOMIn + DEFAIn
  # mPrt_k_DEIn_NDF_src <-  c(0,   0,       5.43)          #DENDFIn
  # mPrt_k_Arg_src <-    c(0,      0.8175,  0)
  # mPrt_k_His_src <-    c(1.675,  1.641,   1.19)	
  # mPrt_k_Ile_src <-    c(0.885,  0.837,   1.08)
  # mPrt_k_Leu_src <-    c(0.466,  0.623,   0.238)
  # mPrt_k_Lys_src <-    c(1.153,  1.235,   1.08)	
  # mPrt_k_Met_src <-    c(1.839,  1.846,   1.91)
  # mPrt_k_Phe_src <-    c(0,      0,       0)
  # mPrt_k_Thr_src <-    c(0,      0,       1.36)
  # mPrt_k_Trp_src <-    c(0.0,    0,       0)
  # mPrt_k_Val_src <-    c(0,      0,       0)
  # mPrt_k_NEAA_src <-   c(0,      0.0925,  0.075)         #NEAA.  Phe, Thr, Trp, and Val not considered.
  # mPrt_k_OthAA_src <-  c(0.0773, 0,       0)             #NEAA + unused EAA.  Added for NRC eqn without Arg as slightly superior.
  # mPrt_k_EAA2_src <- c(-0.00215, -0.002451, -0.00175)    #for utilized EAA only
  # mPrt_Int <- mPrt_Int_src[mPrt_parmset]  #Use mPrt_eqn to select the desired parameters
  # mPrt_k_BW <- mPrt_k_BW_src[mPrt_parmset]
  # mPrt_k_DEInp <- mPrt_k_DEInp_src[mPrt_parmset]         #NRC 2021 and VT 2020 Equations
  # mPrt_k_DigNDF <- mPrt_k_DigNDF_src[mPrt_parmset]
  # mPrt_k_DEIn_StFA <- mPrt_k_DEIn_StFA_src[mPrt_parmset] #VT 2022 Equation
  # mPrt_k_DEIn_NDF <- mPrt_k_DEIn_NDF_src[mPrt_parmset]
  # mPrt_k_NEAA <- mPrt_k_NEAA_src[mPrt_parmset]
  # mPrt_k_OthAA <- mPrt_k_OthAA_src[mPrt_parmset]
  # #Select the correct sum of square EAA term
  # Abs_EAA2b_g <- Abs_EAA2_HILKM_g  #NRC eqn.
  # if(mPrt_eqn == 2){Abs_EAA2b_g <- Abs_EAA2_RHILKM_g}  #VT1 eqn.
  # if(mPrt_eqn == 3){Abs_EAA2b_g <- Abs_EAA2_HILKMT_g}  #VT2 eqn.
  # #following is specific to NRC 2021 eqn
  # Abs_OthAA_g <- Abs_neAA_g + Abs_Arg_g + Abs_Phe_g + Abs_Thr_g + Abs_Trp_g + Abs_Val_g #NRC eqn only.
  # 
  # ################### Calculations to Allow Scaling of the Milk Protein Quadratics ###################
  # #Scale the maximum EAA responses to accommodate high genetic merit herds.  See description of qn by Hanigan et al. 
  # #An_305RHA_MlkNP is 305 mlk NP value passed to the model (280 kg/305d = no adjustment). Doubling,  doubles max mPrt output.
  # K_305RHA_MlkTP = 1.0 #A scalar to adjust the slope if needed.  Assumed to be 1. MDH
  # f_mPrt_max <- 1.0 + K_305RHA_MlkTP * (An_305RHA_MlkTP/280 - 1)  #280kg RHA ~ 930 g mlk NP/d herd average
  # mPrtmx_Arg <- -mPrt_k_Arg_src[mPrt_parmset]^2/(4*mPrt_k_EAA2_src[mPrt_parmset])	#maximum milk protein responses from each AA
  # mPrtmx_His <- -mPrt_k_His_src[mPrt_parmset]^2/(4*mPrt_k_EAA2_src[mPrt_parmset])
  # mPrtmx_Ile <- -mPrt_k_Ile_src[mPrt_parmset]^2/(4*mPrt_k_EAA2_src[mPrt_parmset])
  # mPrtmx_Leu <- -mPrt_k_Leu_src[mPrt_parmset]^2/(4*mPrt_k_EAA2_src[mPrt_parmset])
  # mPrtmx_Lys <- -mPrt_k_Lys_src[mPrt_parmset]^2/(4*mPrt_k_EAA2_src[mPrt_parmset])
  # mPrtmx_Met <- -mPrt_k_Met_src[mPrt_parmset]^2/(4*mPrt_k_EAA2_src[mPrt_parmset])
  # mPrtmx_Phe <- -mPrt_k_Phe_src[mPrt_parmset]^2/(4*mPrt_k_EAA2_src[mPrt_parmset])
  # mPrtmx_Thr <- -mPrt_k_Thr_src[mPrt_parmset]^2/(4*mPrt_k_EAA2_src[mPrt_parmset])
  # mPrtmx_Trp <- -mPrt_k_Trp_src[mPrt_parmset]^2/(4*mPrt_k_EAA2_src[mPrt_parmset])
  # mPrtmx_Val <- -mPrt_k_Val_src[mPrt_parmset]^2/(4*mPrt_k_EAA2_src[mPrt_parmset])
  # Arg_mPrtmx <- -mPrt_k_Arg_src[mPrt_parmset]/(2*mPrt_k_EAA2_src[mPrt_parmset])	#AA input at maximum milk protein response for each AA
  # His_mPrtmx <- -mPrt_k_His_src[mPrt_parmset]/(2*mPrt_k_EAA2_src[mPrt_parmset])
  # Ile_mPrtmx <- -mPrt_k_Ile_src[mPrt_parmset]/(2*mPrt_k_EAA2_src[mPrt_parmset])
  # Leu_mPrtmx <- -mPrt_k_Leu_src[mPrt_parmset]/(2*mPrt_k_EAA2_src[mPrt_parmset])
  # Lys_mPrtmx <- -mPrt_k_Lys_src[mPrt_parmset]/(2*mPrt_k_EAA2_src[mPrt_parmset])
  # Met_mPrtmx <- -mPrt_k_Met_src[mPrt_parmset]/(2*mPrt_k_EAA2_src[mPrt_parmset])
  # Phe_mPrtmx <- -mPrt_k_Phe_src[mPrt_parmset]/(2*mPrt_k_EAA2_src[mPrt_parmset])
  # Thr_mPrtmx <- -mPrt_k_Thr_src[mPrt_parmset]/(2*mPrt_k_EAA2_src[mPrt_parmset])
  # Trp_mPrtmx <- -mPrt_k_Trp_src[mPrt_parmset]/(2*mPrt_k_EAA2_src[mPrt_parmset])
  # Val_mPrtmx <- -mPrt_k_Val_src[mPrt_parmset]/(2*mPrt_k_EAA2_src[mPrt_parmset])
  # 
  # mPrt_Arg_0.1 <- Arg_mPrtmx*0.1*mPrt_k_Arg_src[mPrt_parmset] + (Arg_mPrtmx*0.1)^2*mPrt_k_EAA2_src[mPrt_parmset]	#Milk prt from each EAA
  # mPrt_His_0.1 <- His_mPrtmx*0.1*mPrt_k_His_src[mPrt_parmset] + (His_mPrtmx*0.1)^2*mPrt_k_EAA2_src[mPrt_parmset]	#at 10% of Max response
  # mPrt_Ile_0.1 <- Ile_mPrtmx*0.1*mPrt_k_Ile_src[mPrt_parmset] + (Ile_mPrtmx*0.1)^2*mPrt_k_EAA2_src[mPrt_parmset]
  # mPrt_Leu_0.1 <- Leu_mPrtmx*0.1*mPrt_k_Leu_src[mPrt_parmset] + (Leu_mPrtmx*0.1)^2*mPrt_k_EAA2_src[mPrt_parmset]
  # mPrt_Lys_0.1 <- Lys_mPrtmx*0.1*mPrt_k_Lys_src[mPrt_parmset] + (Lys_mPrtmx*0.1)^2*mPrt_k_EAA2_src[mPrt_parmset]
  # mPrt_Met_0.1 <- Met_mPrtmx*0.1*mPrt_k_Met_src[mPrt_parmset] + (Met_mPrtmx*0.1)^2*mPrt_k_EAA2_src[mPrt_parmset]
  # mPrt_Phe_0.1 <- Phe_mPrtmx*0.1*mPrt_k_Phe_src[mPrt_parmset] + (Phe_mPrtmx*0.1)^2*mPrt_k_EAA2_src[mPrt_parmset]
  # mPrt_Thr_0.1 <- Thr_mPrtmx*0.1*mPrt_k_Thr_src[mPrt_parmset] + (Thr_mPrtmx*0.1)^2*mPrt_k_EAA2_src[mPrt_parmset]
  # mPrt_Trp_0.1 <- Trp_mPrtmx*0.1*mPrt_k_Trp_src[mPrt_parmset] + (Trp_mPrtmx*0.1)^2*mPrt_k_EAA2_src[mPrt_parmset]
  # mPrt_Val_0.1 <- Val_mPrtmx*0.1*mPrt_k_Val_src[mPrt_parmset] + (Val_mPrtmx*0.1)^2*mPrt_k_EAA2_src[mPrt_parmset]
  # 
  # mPrtmx_Arg2 <- mPrtmx_Arg*f_mPrt_max
  # mPrtmx_His2 <- mPrtmx_His*f_mPrt_max
  # mPrtmx_Ile2 <- mPrtmx_Ile*f_mPrt_max
  # mPrtmx_Leu2 <- mPrtmx_Leu*f_mPrt_max
  # mPrtmx_Lys2 <- mPrtmx_Lys*f_mPrt_max
  # mPrtmx_Met2 <- mPrtmx_Met*f_mPrt_max
  # mPrtmx_Phe2 <- mPrtmx_Phe*f_mPrt_max
  # mPrtmx_Thr2 <- mPrtmx_Thr*f_mPrt_max
  # mPrtmx_Trp2 <- mPrtmx_Trp*f_mPrt_max
  # mPrtmx_Val2 <- mPrtmx_Val*f_mPrt_max
  # 
  # #Calculate new scaled linear EAA coeff and a common squared coefficient
  # mPrt_k_Arg <- -(2*sqrt(mPrtmx_Arg2^2-mPrt_Arg_0.1*mPrtmx_Arg2)-2*mPrtmx_Arg2)/(Arg_mPrtmx*0.1)
  # mPrt_k_His <- -(2*sqrt(mPrtmx_His2^2-mPrt_His_0.1*mPrtmx_His2)-2*mPrtmx_His2)/(His_mPrtmx*0.1)
  # mPrt_k_Ile <- -(2*sqrt(mPrtmx_Ile2^2-mPrt_Ile_0.1*mPrtmx_Ile2)-2*mPrtmx_Ile2)/(Ile_mPrtmx*0.1)
  # mPrt_k_Leu <- -(2*sqrt(mPrtmx_Leu2^2-mPrt_Leu_0.1*mPrtmx_Leu2)-2*mPrtmx_Leu2)/(Leu_mPrtmx*0.1)
  # mPrt_k_Lys <- -(2*sqrt(mPrtmx_Lys2^2-mPrt_Lys_0.1*mPrtmx_Lys2)-2*mPrtmx_Lys2)/(Lys_mPrtmx*0.1)
  # mPrt_k_Met <- -(2*sqrt(mPrtmx_Met2^2-mPrt_Met_0.1*mPrtmx_Met2)-2*mPrtmx_Met2)/(Met_mPrtmx*0.1)
  # mPrt_k_Phe <- -(2*sqrt(mPrtmx_Phe2^2-mPrt_Phe_0.1*mPrtmx_Phe2)-2*mPrtmx_Phe2)/(Phe_mPrtmx*0.1)
  # mPrt_k_Thr <- -(2*sqrt(mPrtmx_Thr2^2-mPrt_Thr_0.1*mPrtmx_Thr2)-2*mPrtmx_Thr2)/(Thr_mPrtmx*0.1)
  # mPrt_k_Trp <- -(2*sqrt(mPrtmx_Trp2^2-mPrt_Trp_0.1*mPrtmx_Trp2)-2*mPrtmx_Trp2)/(Trp_mPrtmx*0.1)
  # mPrt_k_Val <- -(2*sqrt(mPrtmx_Val2^2-mPrt_Val_0.1*mPrtmx_Val2)-2*mPrtmx_Val2)/(Val_mPrtmx*0.1)
  # #Convert NA to 0
  # mPrt_k_Arg <- ifelse(is.na(mPrt_k_Arg),0,mPrt_k_Arg)
  # mPrt_k_His <- ifelse(is.na(mPrt_k_His),0,mPrt_k_His)
  # mPrt_k_Ile <- ifelse(is.na(mPrt_k_Ile),0,mPrt_k_Ile)
  # mPrt_k_Leu <- ifelse(is.na(mPrt_k_Leu),0,mPrt_k_Leu)
  # mPrt_k_Lys <- ifelse(is.na(mPrt_k_Lys),0,mPrt_k_Lys)
  # mPrt_k_Met <- ifelse(is.na(mPrt_k_Met),0,mPrt_k_Met)
  # mPrt_k_Phe <- ifelse(is.na(mPrt_k_Phe),0,mPrt_k_Phe)
  # mPrt_k_Thr <- ifelse(is.na(mPrt_k_Thr),0,mPrt_k_Thr)
  # mPrt_k_Trp <- ifelse(is.na(mPrt_k_Trp),0,mPrt_k_Trp)
  # mPrt_k_Val <- ifelse(is.na(mPrt_k_Val),0,mPrt_k_Val)
  # 
  # #Scale the quadratic; can be calculated from any of the AA included in the squared term. All give the same answer
  # mPrt_k_EAA2 <- (2*sqrt(mPrtmx_Met2^2-mPrt_Met_0.1*mPrtmx_Met2)-2*mPrtmx_Met2+mPrt_Met_0.1)/(Met_mPrtmx*0.1)^2
  # 
  # #Predict net protein output in milk
  # Mlk_NP_g <- mPrt_Int + Abs_Arg_g*mPrt_k_Arg + Abs_His_g*mPrt_k_His + Abs_Ile_g*mPrt_k_Ile + 
  #   Abs_Leu_g*mPrt_k_Leu + Abs_Lys_g*mPrt_k_Lys + Abs_Met_g*mPrt_k_Met + Abs_Phe_g*mPrt_k_Phe +
  #   Abs_Thr_g*mPrt_k_Thr + Abs_Trp_g*mPrt_k_Trp + Abs_Val_g*mPrt_k_Val + Abs_neAA_g*mPrt_k_NEAA +
  #   Abs_OthAA_g*mPrt_k_OthAA + Abs_EAA2b_g*mPrt_k_EAA2 + An_DEInp*mPrt_k_DEInp + (An_DigNDF-17.06)*mPrt_k_DigNDF + 
  #   (An_DEStIn+An_DEFAIn+An_DErOMIn)*mPrt_k_DEIn_StFA + An_DENDFIn*mPrt_k_DEIn_NDF + (An_BW-612)*mPrt_k_BW 
  # #BW and DigNDF were centered for the regression
  # 
  # #Calculate the maximal milk protein output at the entered DE, DigNDF, and BW.
  # Mlk_NPmx <- mPrt_Int + mPrtmx_Arg2 + mPrtmx_His2 + mPrtmx_Ile2 + mPrtmx_Leu2 + mPrtmx_Lys2 + 
  #   mPrtmx_Met2 + mPrtmx_Thr2 + mPrtmx_Val2 + An_DEInp*mPrt_k_DEInp + (An_DigNDF-17.06)*mPrt_k_DigNDF + 
  #   (An_BW-612)*mPrt_k_BW + Abs_neAA_g*mPrt_k_NEAA + Abs_OthAA_g*mPrt_k_OthAA
  # 
  # #Calculate predicted Mlk_NP as proportion of max mPrt for reporting purposes.
  # #This value should not exceed ~0.8 for an 18% CP diet with ~60% MP for peak production. (0.8 needs refinement)
  # #If it does, this is an indication that the genetic potential scalar, f_mPrt_max, is set too low.
  # MlkNP_MlkNPmx <- Mlk_NP_g / Mlk_NPmx
  # 
  # Mlk_NP_g <- ifelse(An_StatePhys == "Lactating Cow", Mlk_NP_g, 0)
  
  
  
  
  Trg_Mlk_NP_g <- Trg_MilkProd*1000 * Trg_MilkTPp/100
  Trg_Mlk_NP <- Trg_Mlk_NP_g/1000
  
  if(mPrt_eqn==0) {Mlk_NP_g <- Trg_Mlk_NP_g} #Select Trg_MilkTP or predicted Mlk_NP for remaining calcs.
  An_SWlact <- ifelse(Mlk_NP_g > 0, 1, 0)	#Detect lactation and set a switch for use with other eqns.
  Mlk_NP <- Mlk_NP_g /1000 #kg NP/d
  
  Mlk_CP_g <- Mlk_NP_g / 0.95
  Mlk_CP <- Mlk_CP_g / 1000
  
  #Calculate AA outputs in milk protein
  Mlk_Arg_g <- Mlk_NP_g * Mlk_Arg_TP / 100
  Mlk_His_g <- Mlk_NP_g * Mlk_His_TP / 100
  Mlk_Ile_g <- Mlk_NP_g * Mlk_Ile_TP / 100
  Mlk_Leu_g <- Mlk_NP_g * Mlk_Leu_TP / 100
  Mlk_Lys_g <- Mlk_NP_g * Mlk_Lys_TP / 100
  Mlk_Met_g <- Mlk_NP_g * Mlk_Met_TP / 100
  Mlk_Phe_g <- Mlk_NP_g * Mlk_Phe_TP / 100
  Mlk_Thr_g <- Mlk_NP_g * Mlk_Thr_TP / 100
  Mlk_Trp_g <- Mlk_NP_g * Mlk_Trp_TP / 100
  Mlk_Val_g <- Mlk_NP_g * Mlk_Val_TP / 100
  Mlk_EAA_g <- Mlk_Arg_g + Mlk_His_g + Mlk_Ile_g + Mlk_Leu_g + Mlk_Lys_g + Mlk_Met_g + Mlk_Phe_g + Mlk_Thr_g + Mlk_Trp_g + Mlk_Val_g
  
  
  
  
  # ### Calculate Predicted Gross efficiencies of Use of AA for Milk Protein ###
  # #Milk Protein Efficiency,  as a fraction of Absorbed
  MlkNP_AnMP <- Mlk_NP_g / An_MPIn_g
  # MlkArg_AbsArg <- Mlk_Arg_g / Abs_Arg_g 
  # MlkHis_AbsHis <- Mlk_His_g / Abs_His_g 
  # MlkIle_AbsIle <- Mlk_Ile_g / Abs_Ile_g 
  # MlkLeu_AbsLeu <- Mlk_Leu_g / Abs_Leu_g 
  # MlkLys_AbsLys <- Mlk_Lys_g / Abs_Lys_g 
  # MlkMet_AbsMet <- Mlk_Met_g / Abs_Met_g 
  # MlkPhe_AbsPhe <- Mlk_Phe_g / Abs_Phe_g 
  # MlkThr_AbsThr <- Mlk_Thr_g / Abs_Thr_g 
  # MlkTrp_AbsTrp <- Mlk_Trp_g / Abs_Trp_g 
  # MlkVal_AbsVal <- Mlk_Val_g / Abs_Val_g 
  # MlkEAA_AbsEAA <- Mlk_EAA_g / Abs_EAA_g
  # #Predicted Gross Milk Protein Efficiency, g/g in the diet
  # MlkNP_AnCP <- Mlk_NP_g / (An_CPIn*1000)
  # MlkArg_DtArg <- Mlk_Arg_g / Dt_ArgIn 
  # MlkHis_DtHis <- Mlk_His_g / Dt_HisIn 
  # MlkIle_DtIle <- Mlk_Ile_g / Dt_IleIn 
  # MlkLeu_DtLeu <- Mlk_Leu_g / Dt_LeuIn 
  # MlkLys_DtLys <- Mlk_Lys_g / Dt_LysIn 
  # MlkMet_DtMet <- Mlk_Met_g / Dt_MetIn 
  # MlkPhe_DtPhe <- Mlk_Phe_g / Dt_PheIn 
  # MlkThr_DtThr <- Mlk_Thr_g / Dt_ThrIn 
  # MlkTrp_DtTrp <- Mlk_Trp_g / Dt_TrpIn 
  # MlkVal_DtVal <- Mlk_Val_g / Dt_ValIn 
  
  
  
  ############################################################################################
  #                        Gestation Energy, NP, and AA Use                                  #
  ############################################################################################
  #Gravid Uterus Composition from the predicted composition at d283 of gestation after the model of Koong et. 1975
  #was fit to the composition data of Bell, 1995 and House and Bell, 1993. See Hanigan et al., 2009 for
  #a description of the general approach as applied in the Molly model.
  
  #Create a pregnancy switch for use in calculations.
  An_Preg <- ifelse(An_GestDay > 0 & An_GestDay <= An_GestLength, 1, 0)
  
  GrUterWt_FetBWbrth <- 1.816	#kg of Gravid Uterus/kg of calf birth weight based on 280 d gestation and Bell solutions.
  UterWt_FetBWbrth <- 0.2311;	#kg Maternal Tissue/kg calf weight at parturition from fits to Bell 1995 data
  NE_GrUtWt <- 0.950;		#mcal/kg fresh Gravid Uterus weight at birth which represents the accumulated values
  CP_GrUtWt <- 0.123;		#kg CP/kg fresh Gr Uterus weight
  
  #Gravid uterine, fetal, and uterine (+cotyledons) growth rate constants derived from Bell data
  #An_GestDay=0 shuts this section off.
  GrUter_Ksyn <- 2.43e-2
  GrUter_KsynDecay <- 2.45e-5
  Fet_Ksyn <- 5.16e-2
  Fet_KsynDecay <- 7.59e-5
  Uter_Ksyn <- 2.42e-2		#Derived from Maternal Tissue data by Hanigan et al., 2009
  Uter_KsynDecay <- 3.53e-5
  Uter_Kdeg <- 0.20			#Estimate from Hanigan et al, 2009
  
  #Estimate Maternal Tisue weight (uterus plus caruncles) at any time
  Uter_Wtpart <- Fet_BWbrth * UterWt_FetBWbrth
  Uter_Wt <- 0.204  #Nonpregnant uterine base weight; ideally would be scaled to BW/BWmature, but a small error for young animals
  Uter_Wt <- ifelse(An_AgeDay < 240, 0, Uter_Wt)  #Set Uter_Wt to 0 for young animals
  Uter_Wt <- ifelse(An_GestDay > 0 & An_GestDay <= An_GestLength,  #gestating animal
                    Uter_Wtpart * exp(-(Uter_Ksyn-Uter_KsynDecay*An_GestDay)*(An_GestLength-An_GestDay)), Uter_Wt)
  Uter_Wt <- ifelse(An_GestDay <= 0 & An_LactDay > 0 & An_LactDay < 100, #uterine involution after calving
                    ((Uter_Wtpart-0.204)*exp(-Uter_Kdeg*An_LactDay))+0.204, Uter_Wt)	#LactDay should start at 1, not 0
  Uter_Wt <- ifelse(An_Parity_rl > 0 & Uter_Wt < 0.204, 0.204, Uter_Wt)  #Set the min to 0.204.  Should be scaled to BW, but no data.
  #The above needs to be looked at again.  It doesn't converge back to 0.204 as it should when using the Bell et al. birth weights.  Close but not exact.  Perhaps rounding error, but not sure. MDH
  
  #Estimate Gravid Uterine weight at any time
  GrUter_Wtpart <- Fet_BWbrth * GrUterWt_FetBWbrth
  GrUter_Wt <- Uter_Wt                                               #non-pregnant animal
  GrUter_Wt <- ifelse(An_GestDay > 0 & An_GestDay <= An_GestLength,  #gestating animal
                      GrUter_Wtpart * exp(-(GrUter_Ksyn-GrUter_KsynDecay*An_GestDay)*(An_GestLength-An_GestDay)),
                      GrUter_Wt)
  GrUter_Wt <- ifelse(GrUter_Wt < Uter_Wt, Uter_Wt, GrUter_Wt)  #Shouldn't need this, but just in case, trap bad values
  
  #Estimate Fetal weight at any time
  Fet_Wt <- 0                                                     #open animal
  Fet_Wt <- ifelse(An_GestDay > 0 & An_GestDay <= An_GestLength,  #gestating animal
                   Fet_BWbrth * exp(-(Fet_Ksyn-Fet_KsynDecay*An_GestDay)*(An_GestLength-An_GestDay)), Fet_Wt)
  
  #Estimate rates of fresh tissue growth for the Gravid Uterus, Maternal Repro Tissue, and the Fetus
  Uter_BWgain <- 0  #Open and nonregressing animal
  Uter_BWgain <- ifelse(An_GestDay > 0 & An_GestDay <= An_GestLength,  #gestating animal
                        (Uter_Ksyn - Uter_KsynDecay * An_GestDay) * Uter_Wt, Uter_BWgain)
  Uter_BWgain <- ifelse(An_GestDay <= 0 & An_LactDay > 0 & An_LactDay < 100, #uterine involution after calving
                        -Uter_Kdeg*Uter_Wt, Uter_BWgain)	#kg/d
  
  GrUter_BWgain <- 0       #open animal and nonregressing, kg fresh wt/d
  GrUter_BWgain <- ifelse(An_GestDay > 0 & An_GestDay <= An_GestLength,  #gestating animal
                          (GrUter_Ksyn-GrUter_KsynDecay*An_GestDay)*GrUter_Wt, GrUter_BWgain)
  GrUter_BWgain <- ifelse(An_GestDay <= 0 & An_LactDay > 0 & An_LactDay < 100, #uterine involution after calving
                          Uter_BWgain, GrUter_BWgain)
  Fet_BWgain <- 0	#open animal, kg/d
  Fet_BWgain <- ifelse(An_GestDay > 0 & An_GestDay <= An_GestLength, #gestating animal
                       (Fet_Ksyn-Fet_KsynDecay*An_GestDay)*Fet_Wt, Fet_BWgain)
  Conc_BWgain <- GrUter_BWgain - Uter_BWgain
  
  #Net protein gain in other maternal tissues during late gestation: mammary, intestine, liver, and blood
  #this should be replaced with a growth funncton such as Dijkstra's mammary growth equation. MDH.
  Gest_NPother_g <- 0
  #Gest_CPother_g <- ifelse(An_GestDay>=260, 0.135*6.25*An_MBW,0) #Causes a big jump when it turns on at 260 days pregnant.  Not used.
  #0.135 g/kg is the mean of values from McNeill et al. 1997 and Putnam and Varga, 1998.
  #Gest_NPother_g <- Gest_CPother_g * Body_NP_CP
  #Body_NP_CP is the conversion of CP to TP.
  
  #### Gestation Energy ####
  Gest_REgain <- GrUter_BWgain * NE_GrUtWt;	#This will slightly underestimate release of NE from the regressing uterus
  
  #### Estimate net rates of NP (g/d), and AA (g/d) deposition in the Gravid uterus ####
  Gest_NCPgain_g <- GrUter_BWgain * CP_GrUtWt * 1000
  Gest_NPgain_g <- Gest_NCPgain_g * Body_NP_CP;	#Will slightly underestimate release of NP from the regressing uterus
  Gest_NPuse_g <- Gest_NPgain_g + Gest_NPother_g
  Gest_CPuse_g <- Gest_NPuse_g/Body_NP_CP
  Gest_Arg_g <- Gest_NPuse_g * Body_Arg_TP / 100
  Gest_His_g <- Gest_NPuse_g * Body_His_TP / 100
  Gest_Ile_g <- Gest_NPuse_g * Body_Ile_TP / 100
  Gest_Leu_g <- Gest_NPuse_g * Body_Leu_TP / 100
  Gest_Lys_g <- Gest_NPuse_g * Body_Lys_TP / 100
  Gest_Met_g <- Gest_NPuse_g * Body_Met_TP / 100
  Gest_Phe_g <- Gest_NPuse_g * Body_Phe_TP / 100
  Gest_Thr_g <- Gest_NPuse_g * Body_Thr_TP / 100
  Gest_Trp_g <- Gest_NPuse_g * Body_Trp_TP / 100
  Gest_Val_g <- Gest_NPuse_g * Body_Val_TP / 100
  Gest_EAA_g <- Gest_Arg_g + Gest_His_g + Gest_Ile_g + Gest_Leu_g + Gest_Lys_g + Gest_Met_g + Gest_Phe_g +
    Gest_Thr_g + Gest_Trp_g + Gest_Val_g
  
  # #Gest net deposition, g/g absorbed
  # GestArg_AbsArg <- Gest_Arg_g / Abs_Arg_g 
  # GestHis_AbsHis <- Gest_His_g / Abs_His_g 
  # GestIle_AbsIle <- Gest_Ile_g / Abs_Ile_g 
  # GestLeu_AbsLeu <- Gest_Leu_g / Abs_Leu_g 
  # GestLys_AbsLys <- Gest_Lys_g / Abs_Lys_g 
  # GestMet_AbsMet <- Gest_Met_g / Abs_Met_g 
  # GestPhe_AbsPhe <- Gest_Phe_g / Abs_Phe_g 
  # GestThr_AbsThr <- Gest_Thr_g / Abs_Thr_g 
  # GestTrp_AbsTrp <- Gest_Trp_g / Abs_Trp_g 
  # GestVal_AbsVal <- Gest_Val_g / Abs_Val_g 
  
  
  ############################################################################################
  #                           Body Weight, Body Comp, and BW gain                            #
  ############################################################################################
  BW_BCS <- 0.094 * An_BW  #Each BCS represents 94 g of weight per kg of BW
  An_BWnp <- An_BW - GrUter_Wt  #Non-pregnant BW
  An_BWnp3 <- An_BWnp / (1 + 0.094*(An_BCS - 3)) #BWnp standardized to BCS of 3 using 9.4% of BW/unit of BCS
  
  #### Calculate Gut Fill and EBW so the latter is available for other eqns ####
  An_GutFill_BWmature <- 0.18                                                                    #mature animals
  
  An_GutFill_BW <- 0.06		                     								     #Milk fed calf, kg/kg BW
  # An_GutFill_BW <- ifelse(An_StatePhys=="Calf" & Dt_DMIn_ClfLiq>0.01 & Dt_DMIn_ClfStrt<=0.01 &   #Heavy milk fed veal calf 
  #                           An_BW>0.16*An_BW_mature, 0.09, An_GutFill_BW)	                           
  # An_GutFill_BW <- ifelse(An_StatePhys=="Calf" & Dt_DMIn_ClfLiq > 0.01 & Dt_DMIn_ClfStrt > 0.01, #Milk plus starter fed calf
  #                         0.07, An_GutFill_BW)
  # An_GutFill_BW <- ifelse(An_StatePhys=="Calf" & Dt_DMIn_ClfLiq < 0.01,                          #Weaned calf
  #                         0.15, An_GutFill_BW)
  An_GutFill_BW <- ifelse(An_StatePhys=="Heifer", 0.15, An_GutFill_BW)                           #heifer
  An_GutFill_BW <- ifelse((An_StatePhys=="Dry Cow" |An_StatePhys=="Lactating Cow") & An_Parity_rl > 0, An_GutFill_BWmature, An_GutFill_BW)	 #cow
  # An_GutFill_Wt_Erdman <- 5.9*(Dt_DMIn+InfRum_DMIn+InfSI_DMIn)	#cows only, from Erdman et al. 2017; not used
  
  An_GutFill_Wt <- An_GutFill_BW * An_BWnp
  An_BW_empty <- An_BW - An_GutFill_Wt 	
  An_BWmature_empty <- An_BW_mature*(1-An_GutFill_BWmature)
  An_BWnp_empty <- An_BWnp - An_GutFill_Wt 	#BCS3 Std EBW
  An_BWnp3_empty <- An_BWnp3 - An_GutFill_Wt 	#BCS3 Std EBWnp
  
  #Body Composition, g/g EBW
  Body_Fat_EBW <- 0.067+0.188*An_BW/An_BW_mature
  Body_NonFat_EBW <- 1 - Body_Fat_EBW
  Body_CP_EBW <- 0.215*Body_NonFat_EBW
  Body_Ash_EBW <- 0.056 * Body_NonFat_EBW
  Body_Wat_EBW <- 0.729 * Body_NonFat_EBW
  
  Body_Fat <- An_BWnp_empty * Body_Fat_EBW  #Using a non-pregnant BW
  Body_NonFat <- An_BWnp_empty * Body_NonFat_EBW
  Body_CP <- An_BWnp_empty * Body_NonFat_EBW
  Body_Ash <- An_BWnp_empty * Body_Ash_EBW
  Body_Wat <- An_BWnp_empty * Body_Wat_EBW
  
  #### Body gain and Composition of the Gain ####
  #Gain
  Frm_Gain <- Trg_FrmGain		#kg/d.  Add any predictions of ADG and select Trg or Pred ADG here
  Rsrv_Gain <- Trg_RsrvGain
  Body_Gain <- Frm_Gain + Rsrv_Gain
  An_BodConcgain <- Body_Gain + Conc_BWgain #Minus fetal fluid.
  
  Frm_Gain_empty <- Frm_Gain*(1-An_GutFill_BW)	    #Assume the same gut fill for frame gain
  Frm_Gain_empty <- ifelse(Dt_DMIn_ClfLiq>0 & Dt_DMIn_ClfStrt>0, Frm_Gain*0.91, Frm_Gain_empty) #slightly different for grain & milk fed
  Rsrv_Gain_empty <- Rsrv_Gain                     #Assume no gut fill associated with reserves gain
  Body_Gain_empty <- Frm_Gain_empty + Rsrv_Gain_empty
  
  #Fat Gain
  An_REgain_Calf <- Body_Gain_empty^1.10*An_BW_empty^0.205    #calf RE gain needed here for fat gain, mcal/d
  FatGain_FrmGain  <- ifelse(An_StatePhys == "Calf", 
                             0.0786+0.0370*An_REgain_Calf,   # Calves, ..., g/g EBW
                             (0.067+0.375*An_BW/An_BW_mature)) # Heifers and cows, g/g EBW
  FatGain_FrmGain  <- ifelse(is.na(FatGain_FrmGain),0,FatGain_FrmGain)                 #trap NA when no Body_Gain
  NonFatGain_FrmGain <- 1 - FatGain_FrmGain
  FatGain_RsrvGain <- 0.622
  Frm_Fatgain <- FatGain_FrmGain*Frm_Gain_empty
  Rsrv_Fatgain <- FatGain_RsrvGain*Rsrv_Gain_empty
  Body_Fatgain <- Frm_Fatgain + Rsrv_Fatgain
  Body_NonFatGain <- Body_Gain_empty - Body_Fatgain
  
  #Protein Gain
  CPGain_FrmGain <- 0.201-0.081*An_BW/An_BW_mature  #CP gain / gain for heifers
  NPGain_FrmGain <- CPGain_FrmGain * Body_NP_CP   #Convert to CP to TP gain / gain
  Frm_NPgain <- NPGain_FrmGain * Frm_Gain_empty   #TP gain
  Frm_NPgain <- ifelse(An_StatePhys == "Calf", (166.22*Body_Gain_empty + 6.13*An_REgain_Calf/Body_Gain_empty)/1000, Frm_NPgain)
  Frm_NPgain_g <- Frm_NPgain * 1000
  Frm_CPgain <- Frm_NPgain /  Body_NP_CP   #CP gain
  Frm_CPgain_g <- Frm_CPgain * 1000
  
  CPGain_RsrvGain <- 0.068
  NPGain_RsrvGain <- CPGain_RsrvGain * Body_NP_CP 
  Rsrv_NPgain <- NPGain_RsrvGain * Rsrv_Gain_empty
  Rsrv_NPgain_g <- Rsrv_NPgain * 1000
  Rsrv_CPgain <- CPGain_FrmGain * Rsrv_Gain_empty
  Rsrv_CPgain_g <- Rsrv_CPgain * 1000
  
  Body_NPgain <- Frm_NPgain + Rsrv_NPgain
  Body_CPgain <- Body_NPgain / Body_NP_CP  #CP gain
  Body_NPgain_g <- Body_NPgain * 1000
  Body_CPgain_g <- Body_CPgain * 1000
  
  #Ash Gain
  #AshGain_FrmGain <- ?? #should be defined and added in the future.  No values at this time.
  AshGain_RsrvGain <- 0.02
  #Frm_AshGain <- AshGain_FrmGain * Frm_Gain_empty
  Rsrv_AshGain <- AshGain_RsrvGain * Rsrv_Gain_empty
  #Body_AshGain <- Frm_AshGain + Rsrv_AshGain
  Body_AshGain <- 0.056*Body_NonFatGain  #Alternative method of estimation Body and Frm Ash
  Frm_AshGain <- Body_AshGain
  
  #Water Gain
  #WatGain_FrmGain <- 100 - FatGain_FrmGain - NPGain_FrmGain - AshGain_FrmGain
  WatGain_RsrvGain <- 100 - FatGain_RsrvGain - NPGain_RsrvGain - AshGain_RsrvGain
  #Frm_WatGain <- WatGain_FrmGain * Frm_Gain_empty
  Rsrv_WatGain <- WatGain_RsrvGain * Rsrv_Gain_empty
  #Body_WatGain <- Frm_WatGain + Rsrv_WatGain
  Body_WatGain <- 0.729*Body_NonFatGain #Alternative method of estimation
  Frm_WatGain <- Body_WatGain - Rsrv_WatGain
  
  #AA Gain
  Body_ArgGain_g <- Body_NPgain_g * Body_Arg_TP / 100
  Body_HisGain_g <- Body_NPgain_g * Body_His_TP / 100
  Body_IleGain_g <- Body_NPgain_g * Body_Ile_TP / 100
  Body_LeuGain_g <- Body_NPgain_g * Body_Leu_TP / 100
  Body_LysGain_g <- Body_NPgain_g * Body_Lys_TP / 100
  Body_MetGain_g <- Body_NPgain_g * Body_Met_TP / 100
  Body_PheGain_g <- Body_NPgain_g * Body_Phe_TP / 100
  Body_ThrGain_g <- Body_NPgain_g * Body_Thr_TP / 100
  Body_TrpGain_g <- Body_NPgain_g * Body_Trp_TP / 100
  Body_ValGain_g <- Body_NPgain_g * Body_Val_TP / 100
  Body_EAAGain_g <- Body_ArgGain_g + Body_HisGain_g + Body_IleGain_g + Body_LeuGain_g + Body_LysGain_g +
    Body_MetGain_g + Body_PheGain_g + Body_ThrGain_g + Body_TrpGain_g + Body_ValGain_g
  
  # # As a fraction of absorbed
  # BodyArg_AbsArg <- Body_ArgGain_g / Abs_Arg_g 
  # BodyHis_AbsHis <- Body_HisGain_g / Abs_His_g 
  # BodyIle_AbsIle <- Body_IleGain_g / Abs_Ile_g 
  # BodyLeu_AbsLeu <- Body_LeuGain_g / Abs_Leu_g 
  # BodyLys_AbsLys <- Body_LysGain_g / Abs_Lys_g 
  # BodyMet_AbsMet <- Body_MetGain_g / Abs_Met_g 
  # BodyPhe_AbsPhe <- Body_PheGain_g / Abs_Phe_g 
  # BodyThr_AbsThr <- Body_ThrGain_g / Abs_Thr_g 
  # BodyTrp_AbsTrp <- Body_TrpGain_g / Abs_Trp_g 
  # BodyVal_AbsVal <- Body_ValGain_g / Abs_Val_g 
  
  
  ############################################################################################
  #              Total NP, N, and AA Use and Postabsorptive Efficiency                       #
  ############################################################################################
  #NP use for export protein (maintenance, milk, and body gain)
  
  ############################################################################################
  # Seo
  # An_CPm_Use <- Scrf_CP_g + Fe_CPend_g + Ur_NPend_g
  # 여기선 임시로 NASEM (2016)에 따라 세분화 하지 않고 통으로 계산을 하기 때문에 
  # An_CPm_Use<-3.8 / 0.64 * input_data_rev$shrunk_bw^0.75
  # An_NPm_Use <-An_CPm_Use*Body_NP_CP
  
  # Ur_NPend_g을 제외시켜야 한다. 
  # An_NPm_Use <- Scrf_NP_g + Fe_NPend_g + Ur_NPend_g
  # Scrf_CP_g + Fe_CPend_g = An_CPm_Use - Ur_NPend_g/Body_NP_CP
  # Scrf_NP_g + Fe_NPend_g = An_NPm_Use - Ur_NPend_g
  
  
  # An_CPxprt_g <- Scrf_CP_g + Fe_CPend_g + Mlk_CP_g + Body_CPgain_g  #Initially defined only as true export protein, but it has migrated to include other prod proteins.
  # An_NPxprt_g <- Scrf_NP_g + Fe_NPend_g + Mlk_NP_g + Body_NPgain_g  #Should have changed the name.
  # Trg_NPxprt_g <- Scrf_NP_g + Fe_NPend_g + Trg_Mlk_NP_g + Body_NPgain_g  #Shouldn't these also include Gest??
  
  # Seo
  An_CPxprt_g <- An_CPm_Use - Ur_NPend_g/Body_NP_CP + Mlk_CP_g + Body_CPgain_g  #Initially defined only as true export protein, but it has migrated to include other prod proteins.
  An_NPxprt_g <- An_NPm_Use - Ur_NPend_g + Mlk_NP_g + Body_NPgain_g  #Should have changed the name.
  Trg_NPxprt_g <- An_NPm_Use - Ur_NPend_g + Trg_Mlk_NP_g + Body_NPgain_g  #Shouldn't these also include Gest??
  ############################################################################################
  
  An_CPprod_g <- Mlk_CP_g + Gest_NCPgain_g + Body_CPgain_g #CP use for production.  Be careful not to double count Gain.
  An_NPprod_g <- Mlk_NP_g + Gest_NPgain_g + Body_NPgain_g #NP use for production
  Trg_NPprod_g <- Trg_Mlk_NP_g + Gest_NPgain_g + Body_NPgain_g #NP needed for production target
  An_NPprod_MPIn <- An_NPprod_g / An_MPIn_g
  
  #Total protein and N use, g/d
  # Trg_NPuse_g <- Scrf_NP_g + Fe_NPend_g + Ur_NPend_g + Trg_Mlk_NP_g + Body_NPgain_g + Gest_NPgain_g
  # An_NPuse_g <- Scrf_NP_g + Fe_NPend_g + Ur_NPend_g + Mlk_NP_g + Body_NPgain_g + Gest_NPgain_g  #includes only net use of true protein.  Excludes non-protein maintenance use.
  # An_NCPuse_g <- Scrf_CP_g + Fe_CPend_g + Ur_NPend_g + Mlk_CP_g + Body_CPgain_g + Gest_NCPgain_g  #Net CP use
  
  Trg_NPuse_g <- An_NPm_Use + Trg_Mlk_NP_g + Body_NPgain_g + Gest_NPgain_g
  An_NPuse_g <- An_NPm_Use + Mlk_NP_g + Body_NPgain_g + Gest_NPgain_g  #includes only net use of true protein.  Excludes non-protein maintenance use.
  An_NCPuse_g <- An_CPm_Use + Mlk_CP_g + Body_CPgain_g + Gest_NCPgain_g  #Net CP use
  
  
  
  #An_Nuse_g <- An_CPuse_g * 0.16   #considers NPN fraction of the tissues and export fractions.  Not used as the abbreviation is misleading.
  An_Nprod_g <- (Gest_NCPgain_g + Body_CPgain_g)/6.25 + Mlk_CP_g/6.34
  An_Nprod_NIn <- An_Nprod_g / An_NIn_g
  An_Nprod_DigNIn <- An_Nprod_g / An_DigNtIn_g
  
  # #Total Net AA use (Nutrient Allowable), g/d
  # An_ArgUse_g <- Gest_Arg_g + Mlk_Arg_g + Body_ArgGain_g + Scrf_Arg_g + Fe_ArgMet_g + Ur_ArgEnd_g
  # An_HisUse_g <- Gest_His_g + Mlk_His_g + Body_HisGain_g + Scrf_His_g + Fe_HisMet_g + Ur_HisEnd_g
  # An_IleUse_g <- Gest_Ile_g + Mlk_Ile_g + Body_IleGain_g + Scrf_Ile_g + Fe_IleMet_g + Ur_IleEnd_g
  # An_LeuUse_g <- Gest_Leu_g + Mlk_Leu_g + Body_LeuGain_g + Scrf_Leu_g + Fe_LeuMet_g + Ur_LeuEnd_g
  # An_LysUse_g <- Gest_Lys_g + Mlk_Lys_g + Body_LysGain_g + Scrf_Lys_g + Fe_LysMet_g + Ur_LysEnd_g
  # An_MetUse_g <- Gest_Met_g + Mlk_Met_g + Body_MetGain_g + Scrf_Met_g + Fe_MetMet_g + Ur_MetEnd_g
  # An_PheUse_g <- Gest_Phe_g + Mlk_Phe_g + Body_PheGain_g + Scrf_Phe_g + Fe_PheMet_g + Ur_PheEnd_g
  # An_ThrUse_g <- Gest_Thr_g + Mlk_Thr_g + Body_ThrGain_g + Scrf_Thr_g + Fe_ThrMet_g + Ur_ThrEnd_g
  # An_TrpUse_g <- Gest_Trp_g + Mlk_Trp_g + Body_TrpGain_g + Scrf_Trp_g + Fe_TrpMet_g + Ur_TrpEnd_g
  # An_ValUse_g <- Gest_Val_g + Mlk_Val_g + Body_ValGain_g + Scrf_Val_g + Fe_ValMet_g + Ur_ValEnd_g
  # An_EAAUse_g <- An_ArgUse_g + An_HisUse_g + An_IleUse_g + An_LeuUse_g + An_LysUse_g + An_MetUse_g + 
  #   An_PheUse_g + An_ThrUse_g + An_TrpUse_g + An_ValUse_g 
  # 
  # # Total Net AA efficiency, g/g absorbed
  # AnArgUse_AbsArg <- An_ArgUse_g / Abs_Arg_g 
  # AnHisUse_AbsHis <- An_HisUse_g / Abs_His_g 
  # AnIleUse_AbsIle <- An_IleUse_g / Abs_Ile_g 
  # AnLeuUse_AbsLeu <- An_LeuUse_g / Abs_Leu_g 
  # AnLysUse_AbsLys <- An_LysUse_g / Abs_Lys_g 
  # AnMetUse_AbsMet <- An_MetUse_g / Abs_Met_g 
  # AnPheUse_AbsPhe <- An_PheUse_g / Abs_Phe_g 
  # AnThrUse_AbsThr <- An_ThrUse_g / Abs_Thr_g 
  # AnTrpUse_AbsTrp <- An_TrpUse_g / Abs_Trp_g 
  # AnValUse_AbsVal <- An_ValUse_g / Abs_Val_g 
  # AnEAAUse_AbsEAA <- An_EAAUse_g / Abs_EAA_g 
  # 
  # # Total Net AA Balance, g/d
  # An_ArgBal_g <- Abs_Arg_g - An_ArgUse_g
  # An_HisBal_g <- Abs_His_g - An_HisUse_g
  # An_IleBal_g <- Abs_Ile_g - An_IleUse_g
  # An_LeuBal_g <- Abs_Leu_g - An_LeuUse_g
  # An_LysBal_g <- Abs_Lys_g - An_LysUse_g
  # An_MetBal_g <- Abs_Met_g - An_MetUse_g
  # An_PheBal_g <- Abs_Phe_g - An_PheUse_g
  # An_ThrBal_g <- Abs_Thr_g - An_ThrUse_g
  # An_TrpBal_g <- Abs_Trp_g - An_TrpUse_g
  # An_ValBal_g <- Abs_Val_g - An_ValUse_g
  # An_EAABal_g <- Abs_EAA_g - An_EAAUse_g
  # 
  # #Target postabsorptive efficiencies based on maximum observed efficiencies from Martineau and LaPiere as listed in NRC, Ch. 6.
  # Trg_AbsHis_NPxprtHis <- Eff$Trg_AbsHis_NPHis  
  # Trg_AbsIle_NPxprtIle <- Eff$Trg_AbsIle_NPIle
  # Trg_AbsLeu_NPxprtLeu <- Eff$Trg_AbsLeu_NPLeu
  # Trg_AbsLys_NPxprtLys <- Eff$Trg_AbsLys_NPLys
  # Trg_AbsMet_NPxprtMet <- Eff$Trg_AbsMet_NPMet
  # Trg_AbsPhe_NPxprtPhe <- Eff$Trg_AbsPhe_NPPhe
  # Trg_AbsThr_NPxprtThr <- Eff$Trg_AbsThr_NPThr
  # Trg_AbsTrp_NPxprtTrp <- Eff$Trg_AbsTrp_NPTrp
  # Trg_AbsVal_NPxprtVal <- Eff$Trg_AbsVal_NPVal
  # Trg_AbsEAA_NPxprtEAA <- (Trg_AbsHis_NPxprtHis + Trg_AbsIle_NPxprtIle + Trg_AbsLeu_NPxprtLeu + Trg_AbsLys_NPxprtLys + Trg_AbsMet_NPxprtMet +   #Should be weighted or derived 
  #                            Trg_AbsPhe_NPxprtPhe +Trg_AbsThr_NPxprtThr + Trg_AbsTrp_NPxprtTrp + Trg_AbsVal_NPxprtVal) / 9            #directly from total EAA
  # Trg_AbsArg_NPxprtArg <- Trg_AbsEAA_NPxprtEAA  #none provided thus assumed to be the same as for EAA
  
  ############################################################################################
  # Seo
  # Trg_MP_NPxprt <- Eff$Trg_MP_NP
  Trg_MP_NPxprt <- 0.69
  ############################################################################################
  
  #Estimate the degree of AA imbalance within the EAA as ratios of each Eff to the total EAA Eff.
  #These "Target" ratios are calculated as efficiency target (NRC 2021 Ch. 6) / total EAA eff.
  #Thus they are scaled to Ch. 6 targets.  Ch. 6 values should not be used directly here. Ratio first.
  #The target eff from Ch. 6 are likely not true maximum efficiencies.
  # Trg_ArgEff_EAAEff <- Trg_AbsArg_NPxprtArg / Trg_AbsEAA_NPxprtEAA  
  # Trg_HisEff_EAAEff <- Trg_AbsHis_NPxprtHis / Trg_AbsEAA_NPxprtEAA  #ratio to the mean Trg for each EAA / total EAA Trg of 70.6%
  # Trg_IleEff_EAAEff <- Trg_AbsIle_NPxprtIle / Trg_AbsEAA_NPxprtEAA  #e.g. Ile Trg is 97.3% of 70.6%
  # Trg_LeuEff_EAAEff <- Trg_AbsLeu_NPxprtLeu / Trg_AbsEAA_NPxprtEAA
  # Trg_LysEff_EAAEff <- Trg_AbsLys_NPxprtLys / Trg_AbsEAA_NPxprtEAA
  # Trg_MetEff_EAAEff <- Trg_AbsMet_NPxprtMet / Trg_AbsEAA_NPxprtEAA
  # Trg_PheEff_EAAEff <- Trg_AbsPhe_NPxprtPhe / Trg_AbsEAA_NPxprtEAA
  # Trg_ThrEff_EAAEff <- Trg_AbsThr_NPxprtThr / Trg_AbsEAA_NPxprtEAA
  # Trg_TrpEff_EAAEff <- Trg_AbsTrp_NPxprtTrp / Trg_AbsEAA_NPxprtEAA
  # Trg_ValEff_EAAEff <- Trg_AbsVal_NPxprtVal / Trg_AbsEAA_NPxprtEAA
  # 
  # #Calculate the current ratios for the diet.  This centers the ratio to the prevailing EAA Efficiency   
  # An_ArgEff_EAAEff <- AnArgUse_AbsArg / AnEAAUse_AbsEAA
  # An_HisEff_EAAEff <- AnHisUse_AbsHis / AnEAAUse_AbsEAA
  # An_IleEff_EAAEff <- AnIleUse_AbsIle / AnEAAUse_AbsEAA
  # An_LeuEff_EAAEff <- AnLeuUse_AbsLeu / AnEAAUse_AbsEAA
  # An_LysEff_EAAEff <- AnLysUse_AbsLys / AnEAAUse_AbsEAA
  # An_MetEff_EAAEff <- AnMetUse_AbsMet / AnEAAUse_AbsEAA
  # An_PheEff_EAAEff <- AnPheUse_AbsPhe / AnEAAUse_AbsEAA
  # An_ThrEff_EAAEff <- AnThrUse_AbsThr / AnEAAUse_AbsEAA
  # An_TrpEff_EAAEff <- AnTrpUse_AbsTrp / AnEAAUse_AbsEAA
  # An_ValEff_EAAEff <- AnValUse_AbsVal / AnEAAUse_AbsEAA
  # 
  # #Calculate a relative penalty for each EAA to reflect the degree of imbalance for each.
  # #if the diet eff = Trg_eff then no penalty. f_Imb is a vector of penalty costs for each EAA.
  # #f_Imb should be passed to the model fn rather than handled as a global variable.
  # Imb_Arg <- ((An_ArgEff_EAAEff - Trg_ArgEff_EAAEff) * f_Imb["Arg"])^2
  # Imb_His <- ((An_HisEff_EAAEff - Trg_HisEff_EAAEff) * f_Imb["His"])^2
  # Imb_Ile <- ((An_IleEff_EAAEff - Trg_IleEff_EAAEff) * f_Imb["Ile"])^2
  # Imb_Leu <- ((An_LeuEff_EAAEff - Trg_LeuEff_EAAEff) * f_Imb["Leu"])^2
  # Imb_Lys <- ((An_LysEff_EAAEff - Trg_LysEff_EAAEff) * f_Imb["Lys"])^2
  # Imb_Met <- ((An_MetEff_EAAEff - Trg_MetEff_EAAEff) * f_Imb["Met"])^2
  # Imb_Phe <- ((An_PheEff_EAAEff - Trg_PheEff_EAAEff) * f_Imb["Phe"])^2
  # Imb_Thr <- ((An_ThrEff_EAAEff - Trg_ThrEff_EAAEff) * f_Imb["Thr"])^2
  # Imb_Trp <- ((An_TrpEff_EAAEff - Trg_TrpEff_EAAEff) * f_Imb["Trp"])^2
  # Imb_Val <- ((An_ValEff_EAAEff - Trg_ValEff_EAAEff) * f_Imb["Val"])^2
  # 
  # #Sum the penalty to get a relative imbalance value for the optimizer
  # Imb_EAA <- Imb_Arg + Imb_His + Imb_Ile + Imb_Leu + Imb_Lys + Imb_Met + 
  #   Imb_Phe + Imb_Thr + Imb_Trp + Imb_Val
  
  
  ############################################################################################
  #                     Total MP use and MP Allowable Production                             #
  ############################################################################################
  #Fixed assumed efficiencies of conversion of MP to NP.  These do not consider AA balance or energy effects, 
  #and thus may not be true max values. Greater efficiencies are likely possible given that max observed
  #does not guarantee that a perfect mix of AA and DE was achieved.  Thus they are current Targets subject to revision.
  #These should really be abbreviated as _NP_MP to donote the ratio.
  Kx_MP_NP_Trg  <- Trg_MP_NPxprt   #Target observed Export plus Gain Protein efficiency from NRC 2021, Table 6-6 
  Km_MP_NP_Trg <- Kx_MP_NP_Trg #Maintenance assumed to be equal to target efficiency for export plus gain protein
  Km_MP_NP_Trg <- ifelse(An_StatePhys == "Calf" | An_StatePhys == "Heifer", 0.66, Km_MP_NP_Trg)
  Kl_MP_NP_Trg <- Kx_MP_NP_Trg #Lactation assumed to be equal to target efficiency for export plus gain protein
  
  Ky_MP_NP_Trg <- 0.33         #Gestation MP to NP efficiency from NRC GrUter Growth, 2001 NRC.
  Ky_NP_MP_Trg <- 1.0          #Getation NP to MP efficiency when tissue NP deposition is negative after calving
  
  Kg_MP_NP_Trg <- 0.60 * Body_NP_CP  #Default value for Growth MP to TP.  Shouldn't be used for any.
  Kg_MP_NP_Trg <- ifelse(An_Parity_rl == 0 & An_BW_empty/An_BWmature_empty > 0.12,
                         (0.64 - 0.3*An_BW_empty/An_BWmature_empty) * Body_NP_CP,  #for heifers from 12% until 83% of BW_mature
                         Kg_MP_NP_Trg)
  Kg_MP_NP_Trg <- ifelse(Kg_MP_NP_Trg < 0.394*Body_NP_CP, 0.394*Body_NP_CP*Body_NP_CP, Kg_MP_NP_Trg)  #Trap heifer values less than 0.39 MP to CP
  Kg_MP_NP_Trg <- ifelse(An_StatePhys=="Calf", (0.70 - 0.532*(An_BW/An_BW_mature))*Body_NP_CP, Kg_MP_NP_Trg) #calves
  
  #######################################################
  # Seo
  # Kg_MP_NP_Trg <- ifelse(An_Parity_rl > 0,  Eff$Trg_MP_NP, Kg_MP_NP_Trg)  #Cows
  Kg_MP_NP_Trg <- ifelse(An_Parity_rl > 0,  0.69, Kg_MP_NP_Trg)  #Cows
  #######################################################
  
  
  ######## Estimate MP Allowable Production using Target Production and Target Fixed efficiencies - biased as efficiencies are not fixed
  ############################################################################################
  # Seo
  
  # Fe_MPendUse_g_Trg <- Fe_NPend_g / Km_MP_NP_Trg
  # Fe_MPendUse_g_Trg <- ifelse(An_StatePhys == "Calf" | An_StatePhys == "Heifer", Fe_CPend_g/Km_MP_NP_Trg, Fe_MPendUse_g_Trg) #calves and heifers are CP based.
  # Scrf_MPUse_g_Trg <- Scrf_NP_g / Km_MP_NP_Trg
  # Scrf_MPUse_g_Trg <- ifelse(An_StatePhys == "Calf" | An_StatePhys == "Heifer", Scrf_CP_g/Km_MP_NP_Trg, Scrf_MPUse_g_Trg) #calves and heifers are CP based.
  Ur_MPendUse_g <- Ur_NPend_g
  
  # An_NPm_Use <- Scrf_NP_g + Fe_NPend_g + Ur_NPend_g
  # Scrf_CP_g + Fe_CPend_g = An_CPm_Use - Ur_NPend_g/Body_NP_CP
  # Scrf_NP_g + Fe_NPend_g = An_NPm_Use - Ur_NPend_g
  
  
  Rsrv_MPUse_g_Trg <- Rsrv_NPgain_g / Kg_MP_NP_Trg  #kg MP/d for Reserves NP gain
  Frm_MPUse_g_Trg <- Frm_NPgain_g / Kg_MP_NP_Trg  #kg MP/d for Frame NP gain
  Body_MPUse_g_Trg <- Body_NPgain_g / Kg_MP_NP_Trg  #kg MP/d for NP gain
  Gest_MPUse_g_Trg <- ifelse(Gest_NPuse_g >= 0, Gest_NPuse_g/Ky_MP_NP_Trg, Gest_NPuse_g*Ky_NP_MP_Trg)
  Mlk_MPUse_g_Trg <- Trg_Mlk_NP_g/ Kl_MP_NP_Trg  #kg MP/d for target milk protein lactation
  
  
  # Fe_MPendUse_g_Trg + Scrf_MPUse_g_Trg = Fe_NPend_g / Km_MP_NP_Trg + Scrf_NP_g / Km_MP_NP_Trg
  # Fe_MPendUse_g_Trg + Scrf_MPUse_g_Trg = (Fe_NPend_g + Scrf_NP_g) / Km_MP_NP_Trg
  # Fe_MPendUse_g_Trg + Scrf_MPUse_g_Trg = (An_NPm_Use - Ur_NPend_g) / Km_MP_NP_Trg
  
  # An_MPm_g_Trg <- Fe_MPendUse_g_Trg + Scrf_MPUse_g_Trg + Ur_MPendUse_g 
  An_MPm_g_Trg <- (An_NPm_Use - Ur_NPend_g) / Km_MP_NP_Trg + Ur_MPendUse_g 
  An_MPm_g_Trg <- ifelse(An_StatePhys == "Calf" | An_StatePhys == "Heifer", (An_CPm_Use - Ur_NPend_g/Body_NP_CP)/Km_MP_NP_Trg + Ur_NPend_g/Body_NP_CP, An_MPm_g_Trg) #calves and heifers are CP based.
  An_MPm_g_Trg
  
  # An_MPuse_g_Trg <- An_MPm_g_Trg + Body_MPUse_g_Trg + Gest_MPUse_g_Trg + Mlk_MPUse_g_Trg + Scrf_NP_g / Km_MP_NP_Trg
  # 여기에 Scrf_NP_g를 넣는것은 double account 같은데?
  An_MPuse_g_Trg <- An_MPm_g_Trg + Body_MPUse_g_Trg + Gest_MPUse_g_Trg + Mlk_MPUse_g_Trg
  
  ############################################################################################
  
  #Adjust heifer MPuse target if the MP:ME ratio is below optimum for development.
  #Can't calculate ME before MP, thus estimated ME in the MP:ME ratio using the target NPgain.  Will be incorrect
  #if the animal is lactating or gestating.
  
  ############################################################################################
  # Seo
  # An_MEIn_approx <- An_DEInp + An_DENPNCPIn + (An_DigTPaIn-Body_NPgain)*4.0 + Body_NPgain*En_CP - An_GasEOut
  An_MEIn_approx <- An_MEIn
  ############################################################################################
  
  Min_MPuse_g <- ifelse(An_StatePhys == "Heifer" & An_MPuse_g_Trg < (53-25*An_BW/An_BW_mature) * An_MEIn_approx,
                        (53-25*An_BW/An_BW_mature)*An_MEIn_approx, An_MPuse_g_Trg)
  Diff_MPuse_g <- Min_MPuse_g - An_MPuse_g_Trg
  
  #Adjust MPuse based on Min_MPuse
  Frm_MPUse_g_Trg <- ifelse(An_StatePhys == "Heifer" & Diff_MPuse_g > 0, Frm_MPUse_g_Trg + Diff_MPuse_g, Frm_MPUse_g_Trg) 
  #Recalculate Kg_MP_NP
  Kg_MP_NP_Trg <- ifelse(An_StatePhys == "Heifer" & Diff_MPuse_g > 0, Frm_NPgain_g/Frm_MPUse_g_Trg, Kg_MP_NP_Trg)
  #Recalculate Rsrv and Body_MPUse
  Rsrv_MPUse_g_Trg <- ifelse(An_StatePhys == "Heifer" & Diff_MPuse_g > 0, Rsrv_NPgain_g / Kg_MP_NP_Trg, Rsrv_MPUse_g_Trg) 
  Body_MPUse_g_Trg <- ifelse(An_StatePhys == "Heifer" & Diff_MPuse_g > 0, Body_NPgain_g / Kg_MP_NP_Trg, Body_MPUse_g_Trg) 
  An_MPuse_g_Trg <- An_MPm_g_Trg + Frm_MPUse_g_Trg + Rsrv_MPUse_g_Trg + Gest_MPUse_g_Trg + Mlk_MPUse_g_Trg
  
  
  An_MPBal_g_Trg <- An_MPIn_g - An_MPuse_g_Trg
  
  ############################################################################################
  # Seo
  # Xprt_NP_MP_Trg <- (Scrf_NP_g + Fe_NPend_g + Trg_Mlk_NP_g + Body_NPgain_g) / (An_MPIn_g -  Ur_NPend_g - Gest_MPUse_g_Trg) #Predicted An_NP_MP using Target Milk NP, g/g
  Xprt_NP_MP_Trg <- (An_NPm_Use - Ur_NPend_g + Trg_Mlk_NP_g + Body_NPgain_g) / (An_MPIn_g -  Ur_NPend_g - Gest_MPUse_g_Trg) #Predicted An_NP_MP using Target Milk NP, g/g
  
  ############################################################################################
  
  
  #The above excludes Ur_NPend and Gest_NPgain from the denominator and the numerator as that is how Helene and Roger derived target efficiencies. 
  #Seems incorrect unless one does not consider Urinary endogenous as NP which is inconsistent with the definition.  Not a true, total MP efficiency
  
  #Calculate MP allowable milk and gain using fixed apparent maximal target efficiencies
  An_MPavail_Milk_Trg <- An_MPIn - An_MPuse_g_Trg/1000 + Mlk_MPUse_g_Trg/1000
  Mlk_NP_MPalow_Trg_g <- An_MPavail_Milk_Trg * Kx_MP_NP_Trg * 1000   #g milk NP/d
  Mlk_Prod_MPalow <- Mlk_NP_MPalow_Trg_g / (Trg_MilkTPp/100)/1000 #kg milk/d using Trg milk protein % to predict volume
  
  ####################################
  # Seo
  Mlk_Prod <-Trg_MilkProd
  ####################################
  
  Mlk_Prod <- ifelse(An_StatePhys == "Lactating Cow" & mProd_eqn==3, Mlk_Prod_MPalow, Mlk_Prod)  #Use MP Allowable based predictions
  
  ####################################
  # Seo
  
  # Trg_MPIn_req <- Fe_MPendUse_g_Trg+Scrf_MPUse_g_Trg+Ur_MPendUse_g+Body_MPUse_g_Trg+Gest_MPUse_g_Trg+Trg_Mlk_NP_g/Kl_MP_NP_Trg
  Trg_MPIn_req <- (An_NPm_Use - Ur_NPend_g) / Km_MP_NP_Trg +Ur_MPendUse_g+Body_MPUse_g_Trg+Gest_MPUse_g_Trg+Trg_Mlk_NP_g/Kl_MP_NP_Trg
  ####################################
  
  
  An_MPavail_Gain_Trg <- An_MPIn - An_MPuse_g_Trg/1000 + Body_MPUse_g_Trg/1000
  Body_NPgain_MPalowTrg_g <- An_MPavail_Gain_Trg  * Kg_MP_NP_Trg * 1000   #g NP gain/d
  Body_CPgain_MPalowTrg_g <- Body_NPgain_MPalowTrg_g / Body_NP_CP   #g CP gain/d
  Body_Gain_MPalowTrg_g <- Body_NPgain_MPalowTrg_g / NPGain_FrmGain  #g/d, Assume all is frame gain
  Body_Gain_MPalowTrg <- Body_Gain_MPalowTrg_g / 1000
  
  
  ###### Calculate MP efficiency for Export and Total NP for comparison to the ideal efficiency
  Xprt_NP_MP <- (An_NPm_Use - Ur_NPend_g + Mlk_NP_g + Body_NPgain_g) / (An_MPIn_g - Ur_NPend_g - Gest_MPUse_g_Trg)  
  #MP to NP conversion efficiency assuming 100% efficiency of Ur_NPend.  Should not be named as a K as it is not a constant.  This is apparent efficiency.
  Km_MP_NP <- ifelse(An_StatePhys == "Heifer", 0.69, Xprt_NP_MP) #Assumed equal to efficiency for total proteins except for heifers.
  Kl_MP_NP <- Xprt_NP_MP
  
  ######## Estimate MP Use for Milk NP and Maintenance NP
  
  ####################################
  # Seo
  # Fe_MPendUse_g <- Fe_NPend_g / Km_MP_NP
  # Scrf_MPUse_g <- Scrf_NP_g / Km_MP_NP
  
  Mlk_MPUse_g <- Mlk_NP_g / Kl_MP_NP  #kg MP/d for lactation
  # An_MPuse_g <- Fe_MPendUse_g + Scrf_MPUse_g + Ur_MPendUse_g + Body_MPUse_g_Trg + Gest_MPUse_g_Trg + Mlk_MPUse_g
  An_MPuse_g <- (An_NPm_Use - Ur_NPend_g) / Km_MP_NP_Trg + Ur_MPendUse_g + Body_MPUse_g_Trg + Gest_MPUse_g_Trg + Mlk_MPUse_g
  ####################################
  An_MPuse <- An_MPuse_g / 1000
  An_MPBal_g <- An_MPIn_g - An_MPuse_g  #This will always be 0 given how the efficiencies are calculated. Not informative
  #Compare Kl_MP_NP_Trg with Kl_MP_NP to determine diet effectiveness
  
  An_MP_NP <- An_NPuse_g / An_MPuse_g  #Total MP Efficiency, g/g
  An_NPxprt_MP <- (An_NPuse_g-Ur_NPend_g-Gest_NPuse_g) / (An_MPIn_g-Ur_NPend_g-Gest_MPUse_g_Trg)  #g/g. For comparison to target efficiency, but a duplicate of Xprt_NP_MP.
  An_CP_NP <- An_NPuse_g / (An_CPIn*1000)  #Total CP efficiency, g/g
  
  An_NPBal_g <- An_MPIn_g*An_MP_NP - An_NPuse_g  #Also always 0, thus non-informative
  An_NPBal <- An_NPBal_g / 1000
  
  ######################## Urinary N and Energy Losses ########################
  # Ur_Nout_g <- (An_CPIn*1000 - Fe_CP*1000 - Scrf_CP_g - Fe_CPend_g - Mlk_CP_g - 
  #                 Body_CPgain_g - Gest_CPuse_g) / 6.25
  # Ur_Nout_DigNIn <- Ur_Nout_g/(An_DigCPtIn*1000/6.25)*100
  # Ur_Nout_CPcatab <- Ur_Nout_g - Ur_Nend_g  #primarily AA catab, but also absorbed non-MP N such as PD
  # 
  # Ur_DEout <- 0.0143 * Ur_Nout_g
  # UrDE_DMIn <- Ur_DEout / An_DMIn
  # UrDE_GEIn <- Ur_DEout / An_GEIn
  # UrDE_DEIn <- Ur_DEout / An_DEIn
  
  ###################### Estimated ME and NE Intakes ####################
  # An_MEIn <- An_DEIn - An_GasEOut - Ur_DEout
  # K_DE_ME_ClfDry <- ifelse(An_StatePhys == "Calf" & Dt_DMIn_ClfLiq > 0.015*An_BW & RumDevDisc_Clf > 0, 
  #                          0.93 * 0.9, 0.93)
  # An_MEIn <- ifelse(An_StatePhys == "Calf" & Dt_DMIn_ClfLiq >0, 
  #                   Dt_DEIn_base_ClfLiq*0.96 + Dt_DEIn_base_ClfDry*K_DE_ME_ClfDry, An_MEIn) #no consideration of infusions for calves.
  # An_ME <- An_MEIn / An_DMIn
  # An_ME_GE <- An_MEIn / An_GEIn
  # An_ME_DE <- An_MEIn / An_DEIn
  # An_NEIn <- An_MEIn * 0.66
  # An_NE <- An_NEIn / An_DMIn
  # An_NE_GE <- An_NEIn / An_GEIn
  # An_NE_DE <- An_NEIn / An_DEIn
  # An_NE_ME <- An_NEIn / An_MEIn
  # An_MPIn_MEIn <- An_MPIn_g / An_MEIn    #g/Mcal
  
  
  ##############################################################################################
  #                      Estimated ME and NE Use                                               #
  ##############################################################################################
  
  #### Net Energy of Maintenance Requirements (NEm, mcal/d) ####
  #Unstressed (NS) Maintenance costs NEm, mcal/d
  #Heifers
  An_NEmUse_NS <- 0.10 * An_BW^0.75  #Back calculated from MEm of 0.15 and Km_NE_ME = 0.66
  #Calves
  # An_NEmUse_NS <- ifelse(An_StatePhys == "Calf", 0.0769*An_BW_empty^0.75, An_NEmUse_NS)  #milk or mixed diet
  # An_NEmUse_NS <- ifelse(An_StatePhys == "Calf" & Dt_DMIn_ClfLiq == 0, 0.097*An_BW_empty^0.75, An_NEmUse_NS)  #weaned calf
  #Cows
  An_NEmUse_NS <- ifelse(An_Parity_rl>0, 0.10*An_BW^0.75,  An_NEmUse_NS)
  
  
  #Environmental stress cost (NEm_Env), mcal/d ##
  An_NEmUse_Env <- 0
  An_NEmUse_Env <- ifelse(Env_TempCurr<LCT & An_BW<100, 0.00201*(LCT-Env_TempCurr)*
                            An_MBW,An_NEmUse_Env)							#calves - cold stress
  An_NEmUse_Env <- ifelse(Env_TempCurr>UCT & An_BW<100, 0.00201*(Env_TempCurr-UCT)*
                            An_MBW,An_NEmUse_Env)							#calves - heat stress
  
  #Locomotion costs (NEm_Act), mcal/d ##
  # An_Grazing <- ifelse(Dt_PastIn/Dt_DMIn < 0.005, 0, 1)
  # An_NEm_Act_Graze <- ifelse(Dt_PastIn/Dt_DMIn < 0.005, 0, 
  #                            0.0075*An_MBW*(600-12*Dt_PastSupplIn)/600)
  # An_NEm_Act_Parlor <-  (0.00035*Env_DistParlor/1000) * Env_TripsParlor * An_BW
  # An_NEm_Act_Topo <- 0.0067*Env_Topo/1000 * An_BW
  # An_NEmUse_Act <- An_NEm_Act_Graze + An_NEm_Act_Parlor + An_NEm_Act_Topo
  
  #########################################################################
  # Seo 강제로 추가 활동에 따른 정미에너지 요구량을 0로
  An_NEmUse_Act <- 0
  #########################################################################
  
  #Total Maintenance cost (NEm), mcal/d ##
  An_NEmUse <- An_NEmUse_NS + An_NEmUse_Env + An_NEmUse_Act
  
  
  
  ############ efficiencies of Energy Use (Kxxx), Mcal NE/Mcal ME ######################
  # An_MEIn_ClfDry <- An_MEIn - Dt_MEIn_ClfLiq
  # An_ME_ClfDry <- An_MEIn_ClfDry / (An_DMIn - Dt_DMIn_ClfLiq)
  # An_NE_ClfDry <- 1.1104*An_ME_ClfDry - 0.0946*An_ME_ClfDry^2 + 0.0065*An_ME_ClfDry^3 - 0.7783
  # 
  # ## Maintenance ##
  # Km_ME_NE_Clf <- ifelse(An_StatePhys == "Calf" & An_ME_ClfDry > 0 & An_NE_ClfDry >0 & Dt_DMIn_ClfLiq == 0, 
  #                        An_NE_ClfDry/An_ME_ClfDry,   #Dry feed only
  #                        0.69)                       #mixed dry and liquid feed
  # Km_ME_NE_Clf <- ifelse(An_StatePhys == "Calf" & Dt_DMIn_ClfStrt == 0 & Dt_DMIn_ClfLiq > 0, 0.723, Km_ME_NE_Clf) #Liquid feed only
  Km_ME_NE_Heif <- 0.63
  Km_ME_NE_Cow <- 0.66 #Dry and lactating
  Km_ME_NE <- ifelse(An_StatePhys == "Calf", Km_ME_NE_Clf, Km_ME_NE_Heif)  #calves, Heifer is default
  Km_ME_NE <- ifelse(An_StatePhys=="Lactating Cow" | An_StatePhys=="Dry Cow", Km_ME_NE_Cow, Km_ME_NE)  #Dry and Lactating Cows
  
  #Activity
  #Km_ME_NEact <- 0.66
  
  ## Lactation ##
  Kl_ME_NE <- 0.66
  
  ## Frame (f) Gain (excludes Reserves Gain or Loss) ##
  #Calf frame gain
  # Kf_ME_RE_ClfLiq <- 0.56
  # Kf_ME_RE_ClfDry <- (1.1376*An_DE*0.93 -0.1198*(An_DE*0.93)^2+0.0076*(An_DE*0.93)^3-1.2979)/(An_DE*0.93)
  # Kf_ME_RE_Clf <- Kf_ME_RE_ClfLiq*Dt_DMIn_ClfLiq/Dt_DMIn + Kf_ME_RE_ClfDry*(Dt_DMIn-Dt_DMIn_ClfLiq)/Dt_DMIn
  
  Kf_ME_RE <- ifelse(An_StatePhys == "Calf", Kf_ME_RE_Clf, 0.4)    #Default frame gain is 0.4 for heifers and cows
  
  #Reserves Gain and Loss
  Kr_ME_RE <- 0.60                    #Efficiency of ME to RE for reserves gain, Heifers and dry cows
  Kr_ME_RE <- ifelse(Trg_MilkProd > 0 & Trg_RsrvGain > 0, 0.75, Kr_ME_RE) #Efficiency of ME to Rsrv RE for lactating cows gaining Rsrv
  Kr_ME_RE <- ifelse(Trg_RsrvGain <= 0, 0.89, Kr_ME_RE)                #Efficiency of ME generated for cows losing Rsrv
  
  ##Gestation ##
  Ky_ME_NE <- ifelse(Gest_REgain >= 0, 0.14, 0.89) #Gain from Ferrell et al, 1976, and loss assumed = Rsrv loss
  
  
  
  ############## ME Maintenance Requirements (MEm, mcal/d) ################
  An_MEmUse <- An_NEmUse / Km_ME_NE
  An_MEmUse_NS <- An_NEmUse_NS / Km_ME_NE
  An_MEmUse_Act <- An_NEmUse_Act / Km_ME_NE
  An_MEmUse_Env <- An_NEmUse_Env / Km_ME_NE
  An_NEm_ME <- An_NEmUse / An_MEIn #proportion of MEIn used for maintenance
  An_NEm_DE <- An_NEmUse / An_DEIn #proportion of DEIn used for maintenance
  An_NEmNS_DE <- An_NEmUse_NS / An_DEIn
  An_NEmAct_DE <- An_NEmUse_Act / An_DEIn
  An_NEmEnv_DE <- An_NEmUse_Env / An_DEIn
  
  ################ Energy Available for Production, Mcal/d ######################
  An_NEprod_Avail <- An_NEIn - An_NEmUse  
  An_MEprod_Avail <- An_MEIn - An_MEmUse
  
  ############################# Gestation ###########################################
  Gest_MEuse <- Gest_REgain / Ky_ME_NE
  Gest_NELuse <- Gest_MEuse * Kl_ME_NE  #mcal/d ME required. ??This should not be used, delete.
  Gest_NE_ME <- Gest_MEuse / An_MEIn #proportion of MEIn used for Gestation
  Gest_NE_DE <- Gest_REgain / An_DEIn #proportion of DEIn retained in gravid uterus tissue
  
  ######################## Frame and Reserves Gain ########################
  An_REgain <- 9.4*Body_Fatgain+5.55*Body_CPgain	     #Retained Energy, mcal/d. Does not apply to calves
  Rsrv_NEgain <- 9.4*Rsrv_Fatgain + 5.55*Rsrv_CPgain     #These are really REgain.  Abbreviations on NEgain need to be sorted out. MDH
  Frm_NEgain <- 9.4*Frm_Fatgain + 5.55*Frm_CPgain
  Rsrv_NE_DE <- Rsrv_NEgain / An_DEIn #proportion of DEIn used for Reserves gain
  Frm_NE_DE <- Frm_NEgain / An_DEIn #proportion of DEIn used for Frame gain
  Body_NEgain_BWgain <- An_REgain / Body_Gain #mcal NE/kg BW gain
  Rsrv_MEgain <- Rsrv_NEgain / Kr_ME_RE
  Frm_MEgain <- Frm_NEgain / Kf_ME_RE
  An_MEgain <- Rsrv_MEgain + Frm_MEgain
  An_ME_NEg <- An_REgain / An_MEgain  #A weighted average efficiency based on user entered or prediction frame and reserves gains. Cows only at this time.
  
  Rsrv_NELgain <- Rsrv_MEgain * Kl_ME_NE  #express body energy required in NEL terms
  Frm_NELgain <- Frm_MEgain * Kl_ME_NE
  An_NELgain <- An_MEgain * Kl_ME_NE
  
  An_NEgain_DE <- An_REgain / An_DEIn
  An_NEgain_ME <- An_REgain / An_MEIn
  
  ######################## Lactation Energy ########################
  Trg_MilkLacp <- ifelse(is.na(Trg_MilkLacp),4.78,Trg_MilkLacp)	#use the median if missing
  Trg_MilkLac <- Trg_MilkLacp/100 * Trg_MilkProd
  Trg_NEmilk_Milk <- 9.29*Trg_MilkFatp/100 + 5.85*Trg_MilkTPp/100 + 3.95*Trg_MilkLacp/100
  Trg_NEmilk_Milk <- ifelse(is.na(Trg_NEmilk_Milk), 0.36+9.69*Trg_MilkFatp/100, Trg_NEmilk_Milk) #If milk protein and lactose are not provided, use the Tyrrell and Reid (1965) eqn.
  Trg_Mlk_NEout <- Trg_MilkProd * Trg_NEmilk_Milk
  Trg_Mlk_MEout <- Trg_Mlk_NEout / Kl_ME_NE
  Trg_NEmilk_DEIn <- Trg_Mlk_NEout / An_DEIn
  Trg_MilkProd_EPcor <- 0.327*Trg_MilkProd + (12.97*Trg_MilkFatp/100*Trg_MilkProd) + 
    (7.65*Trg_MilkTPp/100*Trg_MilkProd)  #energy and protein corrected milk
  
  ## Energy Allowable Milk - biased estimates as assumption of all added energy to 1 target is wrong ##
  #An_NEavail_Milk <- An_NEIn - An_NEgain - An_NEmUse - Gest_NELuse ??Don't calculate directly.  Calculate from ME available.
  An_MEavail_Milk <- An_MEIn - An_MEgain - An_MEmUse - Gest_MEuse
  Mlk_Prod_NEalow <- An_MEavail_Milk * Kl_ME_NE / Trg_NEmilk_Milk 	#Energy allowable Milk Production, kg/d
  Mlk_Prod <- ifelse(An_StatePhys == "Lactating Cow" & mProd_eqn==2, Mlk_Prod_NEalow, Mlk_Prod)  #use NE Allowable Milk prediction
  Mlk_Prod <- ifelse(mProd_eqn==4, min(Mlk_Prod_NEalow,Mlk_Prod_MPalow), Mlk_Prod)  #Use min of NE and MP Allowable
  Mlk_Prod_NEalow_EPcor <- 0.327*Mlk_Prod_NEalow + (12.97*Trg_MilkFatp/100*Mlk_Prod_NEalow) + 
    (7.65*Trg_MilkTPp/100*Mlk_Prod_NEalow)  #energy and protein corrected milk
  Mlk_EPcorNEalow_DMIn <- Mlk_Prod_NEalow_EPcor / An_DMIn
  
  #Milk Composition
  #g/g
  MlkNP_Milk <- Mlk_NP_g/1000/Mlk_Prod;	#Milk true protein, g/g
  MlkNP_Milk <- ifelse(An_StatePhys == "Lactating Cow", MlkNP_Milk, 0)
  
  #########################################################################
  # Seo
  # milk fat은 target만
  
  Trg_Mlk_Fat <- Trg_MilkProd * Trg_MilkFatp/100
  Trg_Mlk_Fat_g <- Trg_Mlk_Fat * 1000
  
  #Select Trg_MilkFat or predicted Mlk_Fat for remaining calcs.
  # Mlk_Fat_g <- ifelse(mFat_eqn==0, Trg_Mlk_Fat_g, Mlk_Fatemp_g)
  Mlk_Fat_g <- Trg_Mlk_Fat_g
  Mlk_Fat <- Mlk_Fat_g / 1000	
  #########################################################################
  
  
  MlkFat_Milk <- Mlk_Fat / Mlk_Prod  #Milk Fat, g/g
  
  MlkFat_Milk <- ifelse(An_StatePhys == "Lactating Cow", MlkFat_Milk, 0)
  
  #Percentages
  MlkNP_Milk_p <- MlkNP_Milk*100
  MlkFat_Milk_p <- MlkFat_Milk*100
  
  
  MlkNE_Milk <- 9.29*MlkFat_Milk + 5.85*MlkNP_Milk + 3.95*Trg_MilkLacp/100
  Mlk_NEout <- MlkNE_Milk * Mlk_Prod
  Mlk_MEout <- Mlk_NEout / Kl_ME_NE
  Mlk_NE_DE <- Mlk_NEout / An_DEIn #proportion of DEIn used for milk
  
  ## Total Energy Use, Mcal/d ##
  An_MEuse <- An_MEmUse + An_MEgain + Gest_MEuse + Mlk_MEout
  Trg_MEuse <- An_MEmUse + An_MEgain + Gest_MEuse + Trg_Mlk_MEout
  An_NEuse <- An_NEmUse + An_REgain + Gest_REgain + Mlk_NEout
  Trg_NEuse <- An_NEmUse + An_REgain + Gest_REgain + Trg_Mlk_NEout
  An_NELuse <- An_MEuse * Kl_ME_NE
  Trg_NELuse <- Trg_MEuse * Kl_ME_NE
  
  An_NEprod_GE <- (An_NEuse-An_NEmUse) / An_GEIn  #Total efficiency of GE use
  Trg_NEprod_GE <- (Trg_NEuse-An_NEmUse) / An_GEIn  #Total efficiency of GE use
  An_NEmlk_GE <- Mlk_NEout / An_GEIn  #Efficiency of GE use for milk NE
  Trg_NEmlk_GE <- Trg_Mlk_NEout / An_GEIn  #Efficiency of GE use for milk NE
  
  An_MEbal <- An_MEIn - An_MEuse
  An_NELbal <- An_MEbal * Kl_ME_NE
  An_NEbal <- An_NEIn - An_NEuse
  
  Trg_MEbal <- An_MEIn - Trg_MEuse
  Trg_NELbal <- Trg_MEbal * Kl_ME_NE
  Trg_NEbal <- An_NEIn - Trg_NEuse
  
  An_MPuse_MEuse <- An_MPuse_g / An_MEuse     #g/mcal
  Trg_MPuse_MEuse <- An_MPuse_g_Trg / An_MEuse
  
  ## Energy Allowable Gain at the user specified mix of Frame and Reserves ##
  An_MEavail_Grw <- An_MEIn - An_MEmUse - Gest_MEuse - Mlk_MEout
  #Use a weighted average of Kf and Kr to predict allowable gain at that mix of Frm and Rsrv gain.
  Kg_ME_NE <- Kf_ME_RE*Frm_NEgain/(Frm_NEgain+Rsrv_NEgain) + Kr_ME_RE*Rsrv_NEgain/(Frm_NEgain+Rsrv_NEgain)
  Body_Gain_NEalow <- An_MEavail_Grw * Kg_ME_NE / Body_NEgain_BWgain
  
  
  #Make NEallow have the same comp as the mix of Trg Rsrv and Frm
  An_BodConcgain_NEalow <- Body_Gain_NEalow + Conc_BWgain
  Body_Fatgain_NEalow <- 0.85*(Body_Gain_NEalow/0.85-1.19)/8.21
  Body_NPgain_NEalow <- 0.85 * (1-Body_Fatgain_NEalow/0.85) * 0.215
  
  An_Days_BCSdelta1 <- BW_BCS / Body_Gain_NEalow   #days to gain or lose 1 BCS (9.4% of BW), 5 pt scale.
  
  
  
  ######################################################################################################################
  # final output in MP and ME
  
  An_MEuse<-round(An_MEuse,2)
  An_MEbal<-round(An_MEbal,2)
  An_MPuse_g<-round(An_MPuse_g,0)
  An_MPBal_g<-round(An_MPBal_g,0)
  
  ######################################################################################################################
  
  # 
  # 
  # print(paste("ME requirements for maintenance (Mcal/d) = ",An_MEmUse))
  # print(paste("ME requirements for growth (Mcal/d) = ",An_MEgain))
  # print(paste("ME requirements for gestation (Mcal/d) = ",Gest_MEuse))
  # print(paste("ME requirements for lactation (Mcal/d) = ",Mlk_MEout))
  # cat("\n")
  # print(paste("MP requirements for target (g/d) = ",An_MPuse_g_Trg))
  # 
  # An_MPm_g<-(An_NPm_Use - Ur_NPend_g) / Km_MP_NP_Trg + Ur_MPendUse_g
  # 
  # print(paste("MP requirements for maintenance (g/d) = ",An_MPm_g))
  # print(paste("MP requirements for growth (g/d) = ",Body_MPUse_g_Trg))
  # print(paste("MP requirements for gestation (g/d) = ",Gest_MPUse_g_Trg))
  # print(paste("MP requirements for lactation (g/d) = ",Mlk_MPUse_g))
  # cat("\n")
  
  
  #######################
  # Seo
  #An_MPm_g_Trg <- ifelse(An_StatePhys == "Calf" | An_StatePhys == "Heifer", (An_CPm_Use - Ur_NPend_g/Body_NP_CP)/Km_MP_NP_Trg + Ur_NPend_g/Body_NP_CP, An_MPm_g_Trg) #calves and heifers are CP based.
  #
  #이것 때문에 An_MPuse_g_Trg과 An_MPuse_g가 heifer에서는 달라진다. Trg을 할 때는 CP base로 하기 때문에 더 커진다. 
  #왜그런지 모르겠지만, 지금은 그냥 통과
  #그런데, 착유우에서는 Trg이 오히려 더 값이 적다. 살펴봐야 한다. 
  #######################
  
  return(list(MEreq=An_MEuse,MPreq=An_MPuse_g))
  
}

