# last updated on 20240805

library(tidyverse)
source("./modlib/constants_equations_v3.R")



#=============================================#
# Nutrient requirements based on NASEM (2024) #
#=============================================#

###################################################################################################################
# Variable conversion
# 20240604 현재는 어쩔 수 없이 이렇게 
###################################################################################################################

# Animal_input(an)에서 읽는 animal information
# Model_inputs와 CNUCNM input을 매칭시킴

NASEM_Milk_Prediction<-function(input_data_rev,feed_data_rev, diet_composition_rev){
  # DietID <- as.numeric(an$DietID)  #need to maintain TrtID as an input for the function to work with meta data.
  An_StatePhys <- ifelse(input_data_rev$stage_name == "calf", "Calf",
                         ifelse(input_data_rev$stage_name == "growing", "Heifer",
                                ifelse(input_data_rev$stage_name == "lactating", "Lactating Cow",
                                       ifelse(input_data_rev$stage_name == "drying", "Dry Cow", NA))))
  An_Breed <- input_data_rev$breed_name
  An_305RHA_MlkTP <- 1.02 #as.numeric(ref_milk_yield.kg*ref_milk_tp.p/100)
  An_BW_mature <- as.numeric(input_data_rev$mature_bw)  #note case is wrong for M in mature
  An_AgeDay <- as.numeric(input_data_rev$age.month*365)
  An_BW <- as.numeric(input_data_rev$full_bw)
  An_BCS <- as.numeric(input_data_rev$bcs_dairy)
  An_Parity_rl <- min(as.numeric(input_data_rev$lact_no),2) 
  An_LactDay <- as.numeric(input_data_rev$milk.day)
  
  An_GestLength <- 283 #as.numeric(pregnancy.day)
  An_AgeCalv1st <- as.numeric(input_data_rev$tca.month*30.4) # Deleted from version 2020-02-15
  
  Monensin_eqn  <- 0 # added to version 2020-02-15
  
  An_AgeConcept1st <- An_AgeCalv1st-283 #An_AgeCalv1st-pregnancy.day
  An_GestDay <- as.numeric(input_data_rev$preg.day)
  An_DIMConcept <- as.numeric(min(input_data_rev$ci.month*30.4-pregnancy.day,input_data_rev$milk.day))
  
  Env_Topo <- 0
  Env_DistParlor <- 0
  Env_DistParlor <- ifelse(is.na(Env_DistParlor), 0, Env_DistParlor)  #Abbas needs to provide a default value for this
  Env_TripsParlor <- 0
  Env_TripsParlor <- ifelse(is.na(Env_TripsParlor), 4, Env_TripsParlor)  #Abbas needs to provide a default value for this
  Env_TempCurr <- 15
  Env_TempCurr <- ifelse(is.na(Env_TempCurr), 24, Env_TempCurr)  #Abbas needs to provide a default value for this
  
  Fet_BWbrth <- as.numeric(input_data_rev$calf_bw)
  Trg_RsrvGain <- 0
  Trg_FrmGain <- as.numeric(input_data_rev$target_adg)
  Trg_MilkProd <- as.numeric(input_data_rev$milk_yield)
  Trg_MilkFatp <- as.numeric(input_data_rev$milk_fat)
  Trg_MilkTPp <- as.numeric(input_data_rev$milk_cp*0.951)
  Trg_MilkLacp <- 4.85
  
  Trg_Dt_DMIn <- as.numeric(diet_composition_rev$target_dmi)
  
  # 이것은 diet에서 읽음
  Fd_DMInp <- as.numeric(feed_data_rev$dm.kg/diet_composition_rev$target_dmi)
  
  An_AgeDryFdStart <- 14
  
  # DMIn_eqn <- as.numeric(an$DMIn_eqn)
  FrmGain_eqn <- 0
  RsrvGain_eqn <- 0
  # RUP_eqn <- as.numeric(an$RUP_eqn)
  # mFat_eqn <- as.numeric(an$mFat_eqn)
  # MiN_eqn <- as.numeric(an$MiN_eqn)
  mLac_eqn <- 0
  mProd_eqn <- 0
  mPrt_eqn <- 0
  # #... mPrt_eqn <- 1 #temp override
  # Use_DNDF_IV <- as.numeric(an$Use_DNDF_IV)
  # message("Use_DNDF_IV = ", Use_DNDF_IV)
  # 
  # # two new flags. Their names in R-Code are different than thier name in C-Sharp
  # RumDevDisc_Clf <- as.numeric(an$Discount_ME_eqn)
  # NonMilkCP_ClfLiq <- as.numeric(an$Milk_Replacer_eqn)
  
  #################################################
  # Seo - to prevent errors in calf equations
  Dt_DMIn_ClfLiq<-0
  Dt_DMIn_ClfStrt<-0
  #################################################
  
  ##### Fill missing inputs with 0 and add scalars as needed to the f DF for use in Diet Calculations ###########
  #Should also check for missing values in the inputs and trap them or stop the function.
  
  #################################################
  # Don't know
  # f$An_StatePhys <- as.vector(An_StatePhys)   
  #################################################
  
  An_GestDay <- ifelse(An_GestDay < 0 | is.na(An_GestDay), 0, An_GestDay);	#Trap NA and negative values
  An_GestDay <- ifelse(An_GestDay > An_GestLength + 10, 0,  An_GestDay)
  
  #Determine some additional physiology values
  An_PrePartDay <- An_GestDay - An_GestLength
  An_PrePartWk <- An_PrePartDay/7
  
  #Calculate day postpartum and trap nonsense values
  An_PostPartDay <- ifelse(An_LactDay <= 0, 0, An_LactDay)
  An_PostPartDay <- ifelse(An_LactDay > 100, 100, An_LactDay)
  
  An_MBW <- An_BW^0.75
  Trg_BWgain <- Trg_FrmGain + Trg_RsrvGain		#This could also be generated by prediction equations
  Trg_BWgain_g <- Trg_BWgain * 1000
  
  #Determine lower (LCT) and upper (UCT) critical temperatures, degrees C for thermal stress
  LCT <- 15						#calf < 3 wks of age
  LCT <- ifelse(An_AgeDay > 21, 5, LCT)	#calf > 3 wks of age
  UCT <- 25						#calf
  
  
  
  
  ###################################################################################################################
  # supply 모델에서 계산된 Nutrient intake 계산 결과를 여기에
  
  An_DMIn<-diet_composition_rev$target_dmi
  
  An_MPIn_g<-diet_composition_rev$diet_mp.g
  An_MPIn <- An_MPIn_g / 1000
  An_CPIn <- diet_composition_rev$target_dmi*diet_composition_rev$diet_cp.p/100
  An_NIn_g <- An_CPIn*0.16*1000
  
  # RDP + RUP*0.8이 digestible 
  An_DigNtIn_g<-((100-diet_composition_rev$diet_rupx.p.cp)/100 + diet_composition_rev$diet_rupx.p.cp/100*0.8)*An_NIn_g
  
  An_GEIn<-diet_composition_rev$diet_ge.mcal.kg*diet_composition_rev$target_dmi
  An_DEIn<-diet_composition_rev$diet_de.mcal.kg*diet_composition_rev$target_dmi
  An_MEIn<-diet_composition_rev$diet_me.mcal.kg*diet_composition_rev$target_dmi
  # 이것은 NASEM(2021)에 따라
  An_NEIn <- An_MEIn * 0.66
  
  ###################################################################################################################
  
  # 유지방 함량 예측
  #########################################################################################################################################
  # 20240805
  # prediction of milk fat milk yield
  
  
  ############################################################################################
  #                            Milk Fat Predictions from Daley et al.                        #
  ############################################################################################
  
  Dt_DMIn<-Trg_Dt_DMIn
  
  An_LactDay_MlkPred <- ifelse(An_LactDay <= 375, An_LactDay, 375)  #Cap DIM at 375 d to prevent the polynomial from getting out of range.
  Mlk_Fatemp_g <- 453 - 1.42*An_LactDay_MlkPred + 24.52*(Dt_DMIn-Dt_FAIn) + 0.41*Dt_DigC160In*1000 + 
    1.80*Dt_DigC183In*1000 + 1.45 * Abs_Ile_g + 1.34*Abs_Met_g
  Mlk_Fatemp_g <- ifelse(An_StatePhys == "Lactating Cow", Mlk_Fatemp_g, 0)
  Trg_Mlk_Fat <- Trg_MilkProd * Trg_MilkFatp/100
  Trg_Mlk_Fat_g <- Trg_Mlk_Fat * 1000
  
  #Select Trg_MilkFat or predicted Mlk_Fat for remaining calcs.
  Mlk_Fat_g <- ifelse(mFat_eqn==0, Trg_Mlk_Fat_g, Mlk_Fatemp_g)
  Mlk_Fat <- Mlk_Fat_g / 1000	
  
  #need to add calculations of milk fat output of each FA and the efficiency of conversion
  
  ################################################################################################
  # Milk volume predictions from target or predicted milk protein, milk fat, BW, DIM, and Parity #
  ################################################################################################
  #Component based milk production prediction; derived by regression from predicted milk protein and milk fat.
  Mlk_Prod_comp <- 4.541 + 11.13*Mlk_NP + 2.648*Mlk_Fat + 0.1829 * An_DEIn - 0.06257*(An_LactDay_MlkPred-137.1) + 
    2.766e-4*(An_LactDay_MlkPred-137.1)^2 + 1.603e-6*(An_LactDay_MlkPred-137.1)^3 - 7.397e-9*(An_LactDay_MlkPred-137.1)^4 + 
    1.567*(An_Parity_rl-1)  #Holstein equation
  Mlk_Prod_comp <- ifelse(An_Breed == "Jersey", Mlk_Prod_comp - 3.400, Mlk_Prod_comp)
  Mlk_Prod_comp <- ifelse(An_Breed != "Jersey" & An_Breed != "Holstein", Mlk_Prod_comp - 1.526, Mlk_Prod_comp)
  
  #Milk production from component predictions or as entered by the user
  Mlk_Prod <- ifelse(An_StatePhys == "Lactating Cow" & mProd_eqn==1, Mlk_Prod_comp, Trg_MilkProd)
  
  #########################################################################################################################################
  
}